// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.18.1
// source: rpc/c2/agents.proto

package c2

import (
	c2 "github.com/d3c3ptive/aims/proto/c2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentFilters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxResults int64 `protobuf:"varint,1,opt,name=MaxResults,proto3" json:"MaxResults,omitempty"`
}

func (x *AgentFilters) Reset() {
	*x = AgentFilters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_c2_agents_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentFilters) ProtoMessage() {}

func (x *AgentFilters) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_c2_agents_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentFilters.ProtoReflect.Descriptor instead.
func (*AgentFilters) Descriptor() ([]byte, []int) {
	return file_rpc_c2_agents_proto_rawDescGZIP(), []int{0}
}

func (x *AgentFilters) GetMaxResults() int64 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

type CreateAgentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filters *AgentFilters `protobuf:"bytes,1,opt,name=Filters,proto3" json:"Filters,omitempty"`
	Agents  []*c2.Agent   `protobuf:"bytes,2,rep,name=Agents,proto3" json:"Agents,omitempty"`
}

func (x *CreateAgentRequest) Reset() {
	*x = CreateAgentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_c2_agents_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentRequest) ProtoMessage() {}

func (x *CreateAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_c2_agents_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentRequest.ProtoReflect.Descriptor instead.
func (*CreateAgentRequest) Descriptor() ([]byte, []int) {
	return file_rpc_c2_agents_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAgentRequest) GetFilters() *AgentFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *CreateAgentRequest) GetAgents() []*c2.Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

type CreateAgentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Agents []*c2.Agent `protobuf:"bytes,1,rep,name=Agents,proto3" json:"Agents,omitempty"`
}

func (x *CreateAgentResponse) Reset() {
	*x = CreateAgentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_c2_agents_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentResponse) ProtoMessage() {}

func (x *CreateAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_c2_agents_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentResponse.ProtoReflect.Descriptor instead.
func (*CreateAgentResponse) Descriptor() ([]byte, []int) {
	return file_rpc_c2_agents_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAgentResponse) GetAgents() []*c2.Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

type ReadAgentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filters *AgentFilters `protobuf:"bytes,1,opt,name=Filters,proto3" json:"Filters,omitempty"`
	Agent   *c2.Agent     `protobuf:"bytes,2,opt,name=Agent,proto3" json:"Agent,omitempty"`
}

func (x *ReadAgentRequest) Reset() {
	*x = ReadAgentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_c2_agents_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAgentRequest) ProtoMessage() {}

func (x *ReadAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_c2_agents_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAgentRequest.ProtoReflect.Descriptor instead.
func (*ReadAgentRequest) Descriptor() ([]byte, []int) {
	return file_rpc_c2_agents_proto_rawDescGZIP(), []int{3}
}

func (x *ReadAgentRequest) GetFilters() *AgentFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *ReadAgentRequest) GetAgent() *c2.Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

type ReadAgentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Agents []*c2.Agent `protobuf:"bytes,1,rep,name=Agents,proto3" json:"Agents,omitempty"`
}

func (x *ReadAgentResponse) Reset() {
	*x = ReadAgentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_c2_agents_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAgentResponse) ProtoMessage() {}

func (x *ReadAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_c2_agents_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAgentResponse.ProtoReflect.Descriptor instead.
func (*ReadAgentResponse) Descriptor() ([]byte, []int) {
	return file_rpc_c2_agents_proto_rawDescGZIP(), []int{4}
}

func (x *ReadAgentResponse) GetAgents() []*c2.Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

type UpsertAgentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filters *AgentFilters `protobuf:"bytes,1,opt,name=Filters,proto3" json:"Filters,omitempty"`
	Agents  []*c2.Agent   `protobuf:"bytes,2,rep,name=Agents,proto3" json:"Agents,omitempty"`
}

func (x *UpsertAgentRequest) Reset() {
	*x = UpsertAgentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_c2_agents_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertAgentRequest) ProtoMessage() {}

func (x *UpsertAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_c2_agents_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertAgentRequest.ProtoReflect.Descriptor instead.
func (*UpsertAgentRequest) Descriptor() ([]byte, []int) {
	return file_rpc_c2_agents_proto_rawDescGZIP(), []int{5}
}

func (x *UpsertAgentRequest) GetFilters() *AgentFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *UpsertAgentRequest) GetAgents() []*c2.Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

type UpsertAgentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Agents []*c2.Agent `protobuf:"bytes,1,rep,name=Agents,proto3" json:"Agents,omitempty"`
}

func (x *UpsertAgentResponse) Reset() {
	*x = UpsertAgentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_c2_agents_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertAgentResponse) ProtoMessage() {}

func (x *UpsertAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_c2_agents_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertAgentResponse.ProtoReflect.Descriptor instead.
func (*UpsertAgentResponse) Descriptor() ([]byte, []int) {
	return file_rpc_c2_agents_proto_rawDescGZIP(), []int{6}
}

func (x *UpsertAgentResponse) GetAgents() []*c2.Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

type DeleteAgentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Agents []*c2.Agent `protobuf:"bytes,1,rep,name=Agents,proto3" json:"Agents,omitempty"`
}

func (x *DeleteAgentRequest) Reset() {
	*x = DeleteAgentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_c2_agents_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgentRequest) ProtoMessage() {}

func (x *DeleteAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_c2_agents_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgentRequest.ProtoReflect.Descriptor instead.
func (*DeleteAgentRequest) Descriptor() ([]byte, []int) {
	return file_rpc_c2_agents_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteAgentRequest) GetAgents() []*c2.Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

type DeleteAgentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Agents []*c2.Agent `protobuf:"bytes,1,rep,name=Agents,proto3" json:"Agents,omitempty"`
}

func (x *DeleteAgentResponse) Reset() {
	*x = DeleteAgentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_c2_agents_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgentResponse) ProtoMessage() {}

func (x *DeleteAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_c2_agents_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgentResponse.ProtoReflect.Descriptor instead.
func (*DeleteAgentResponse) Descriptor() ([]byte, []int) {
	return file_rpc_c2_agents_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteAgentResponse) GetAgents() []*c2.Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

var File_rpc_c2_agents_proto protoreflect.FileDescriptor

var file_rpc_c2_agents_proto_rawDesc = []byte{
	0x0a, 0x13, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x32, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x63, 0x32, 0x1a, 0x0e, 0x63, 0x32, 0x2f, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a, 0x0c, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x4d, 0x61, 0x78,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x4d,
	0x61, 0x78, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x63, 0x0a, 0x12, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x2a, 0x0a, 0x07, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x63, 0x32, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x73, 0x52, 0x07, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x12, 0x21, 0x0a, 0x06, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x63, 0x32,
	0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x38,
	0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x06, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x63, 0x32, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x52, 0x06, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x5f, 0x0a, 0x10, 0x52, 0x65, 0x61, 0x64,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x07,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x63, 0x32, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x52,
	0x07, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x12, 0x1f, 0x0a, 0x05, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x63, 0x32, 0x2e, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x52, 0x05, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x22, 0x36, 0x0a, 0x11, 0x52, 0x65, 0x61,
	0x64, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21,
	0x0a, 0x06, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09,
	0x2e, 0x63, 0x32, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x73, 0x22, 0x63, 0x0a, 0x12, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x07, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x32, 0x2e, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x52, 0x07, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x73, 0x12, 0x21, 0x0a, 0x06, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x63, 0x32, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x06,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x38, 0x0a, 0x13, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a,
	0x06, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x63, 0x32, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x73,
	0x22, 0x37, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x06, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x63, 0x32, 0x2e, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x52, 0x06, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x38, 0x0a, 0x13, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x21, 0x0a, 0x06, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x63, 0x32, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x73, 0x32, 0xf6, 0x01, 0x0a, 0x06, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x3b,
	0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x16, 0x2e, 0x63, 0x32, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x17, 0x2e, 0x63, 0x32, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x04, 0x52,
	0x65, 0x61, 0x64, 0x12, 0x14, 0x2e, 0x63, 0x32, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x63, 0x32, 0x2e, 0x52,
	0x65, 0x61, 0x64, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x3b, 0x0a, 0x06, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x12, 0x16, 0x2e, 0x63,
	0x32, 0x2e, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x63, 0x32, 0x2e, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x3b, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x16, 0x2e, 0x63, 0x32, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x17, 0x2e, 0x63, 0x32, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x65, 0x0a, 0x06,
	0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x32, 0x42, 0x0b, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x64, 0x33, 0x63, 0x33, 0x70, 0x74, 0x69, 0x76, 0x65, 0x2f, 0x61, 0x69, 0x6d, 0x73,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x32, 0xa2, 0x02, 0x03,
	0x43, 0x58, 0x58, 0xaa, 0x02, 0x02, 0x43, 0x32, 0xca, 0x02, 0x02, 0x43, 0x32, 0xe2, 0x02, 0x0e,
	0x43, 0x32, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02,
	0x02, 0x43, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_c2_agents_proto_rawDescOnce sync.Once
	file_rpc_c2_agents_proto_rawDescData = file_rpc_c2_agents_proto_rawDesc
)

func file_rpc_c2_agents_proto_rawDescGZIP() []byte {
	file_rpc_c2_agents_proto_rawDescOnce.Do(func() {
		file_rpc_c2_agents_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_c2_agents_proto_rawDescData)
	})
	return file_rpc_c2_agents_proto_rawDescData
}

var file_rpc_c2_agents_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_rpc_c2_agents_proto_goTypes = []interface{}{
	(*AgentFilters)(nil),        // 0: c2.AgentFilters
	(*CreateAgentRequest)(nil),  // 1: c2.CreateAgentRequest
	(*CreateAgentResponse)(nil), // 2: c2.CreateAgentResponse
	(*ReadAgentRequest)(nil),    // 3: c2.ReadAgentRequest
	(*ReadAgentResponse)(nil),   // 4: c2.ReadAgentResponse
	(*UpsertAgentRequest)(nil),  // 5: c2.UpsertAgentRequest
	(*UpsertAgentResponse)(nil), // 6: c2.UpsertAgentResponse
	(*DeleteAgentRequest)(nil),  // 7: c2.DeleteAgentRequest
	(*DeleteAgentResponse)(nil), // 8: c2.DeleteAgentResponse
	(*c2.Agent)(nil),            // 9: c2.Agent
}
var file_rpc_c2_agents_proto_depIdxs = []int32{
	0,  // 0: c2.CreateAgentRequest.Filters:type_name -> c2.AgentFilters
	9,  // 1: c2.CreateAgentRequest.Agents:type_name -> c2.Agent
	9,  // 2: c2.CreateAgentResponse.Agents:type_name -> c2.Agent
	0,  // 3: c2.ReadAgentRequest.Filters:type_name -> c2.AgentFilters
	9,  // 4: c2.ReadAgentRequest.Agent:type_name -> c2.Agent
	9,  // 5: c2.ReadAgentResponse.Agents:type_name -> c2.Agent
	0,  // 6: c2.UpsertAgentRequest.Filters:type_name -> c2.AgentFilters
	9,  // 7: c2.UpsertAgentRequest.Agents:type_name -> c2.Agent
	9,  // 8: c2.UpsertAgentResponse.Agents:type_name -> c2.Agent
	9,  // 9: c2.DeleteAgentRequest.Agents:type_name -> c2.Agent
	9,  // 10: c2.DeleteAgentResponse.Agents:type_name -> c2.Agent
	1,  // 11: c2.Agents.Create:input_type -> c2.CreateAgentRequest
	3,  // 12: c2.Agents.Read:input_type -> c2.ReadAgentRequest
	5,  // 13: c2.Agents.Upsert:input_type -> c2.UpsertAgentRequest
	7,  // 14: c2.Agents.Delete:input_type -> c2.DeleteAgentRequest
	2,  // 15: c2.Agents.Create:output_type -> c2.CreateAgentResponse
	4,  // 16: c2.Agents.Read:output_type -> c2.ReadAgentResponse
	6,  // 17: c2.Agents.Upsert:output_type -> c2.UpsertAgentResponse
	8,  // 18: c2.Agents.Delete:output_type -> c2.DeleteAgentResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_rpc_c2_agents_proto_init() }
func file_rpc_c2_agents_proto_init() {
	if File_rpc_c2_agents_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_c2_agents_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentFilters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_c2_agents_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAgentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_c2_agents_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAgentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_c2_agents_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadAgentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_c2_agents_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadAgentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_c2_agents_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpsertAgentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_c2_agents_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpsertAgentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_c2_agents_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAgentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_c2_agents_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAgentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_c2_agents_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_c2_agents_proto_goTypes,
		DependencyIndexes: file_rpc_c2_agents_proto_depIdxs,
		MessageInfos:      file_rpc_c2_agents_proto_msgTypes,
	}.Build()
	File_rpc_c2_agents_proto = out.File
	file_rpc_c2_agents_proto_rawDesc = nil
	file_rpc_c2_agents_proto_goTypes = nil
	file_rpc_c2_agents_proto_depIdxs = nil
}
