package c2



import (
	"github.com/gofrs/uuid"
	"gorm.io/gorm"
)



// BeforeCreate - GORM-specific autogenerated helpers.
func (agent *AgentORM) BeforeCreate(tx *gorm.DB) (err error) {
    id, err := uuid.NewV4()
	if err != nil {
		return err
	}
    agent.Id = id.String()

    return nil
}



// BeforeCreate - GORM-specific autogenerated helpers.
func (beacon *BeaconORM) BeforeCreate(tx *gorm.DB) (err error) {
    id, err := uuid.NewV4()
	if err != nil {
		return err
	}
    beacon.Id = id.String()

    return nil
}



// BeforeCreate - GORM-specific autogenerated helpers.
func (task *TaskORM) BeforeCreate(tx *gorm.DB) (err error) {
    id, err := uuid.NewV4()
	if err != nil {
		return err
	}
    task.Id = id.String()

    return nil
}



