// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.18.1
// source: host/pb/rpc/hosts.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Hosts_Create_FullMethodName = "/hosts.Hosts/Create"
	Hosts_Read_FullMethodName   = "/hosts.Hosts/Read"
	Hosts_Upsert_FullMethodName = "/hosts.Hosts/Upsert"
	Hosts_Delete_FullMethodName = "/hosts.Hosts/Delete"
)

// HostsClient is the client API for Hosts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HostsClient interface {
	// General
	Create(ctx context.Context, in *CreateHostRequest, opts ...grpc.CallOption) (*CreateHostResponse, error)
	Read(ctx context.Context, in *ReadHostRequest, opts ...grpc.CallOption) (*ReadHostResponse, error)
	Upsert(ctx context.Context, in *UpsertHostRequest, opts ...grpc.CallOption) (*UpsertHostResponse, error)
	Delete(ctx context.Context, in *DeleteHostRequest, opts ...grpc.CallOption) (*DeleteHostResponse, error)
}

type hostsClient struct {
	cc grpc.ClientConnInterface
}

func NewHostsClient(cc grpc.ClientConnInterface) HostsClient {
	return &hostsClient{cc}
}

func (c *hostsClient) Create(ctx context.Context, in *CreateHostRequest, opts ...grpc.CallOption) (*CreateHostResponse, error) {
	out := new(CreateHostResponse)
	err := c.cc.Invoke(ctx, Hosts_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostsClient) Read(ctx context.Context, in *ReadHostRequest, opts ...grpc.CallOption) (*ReadHostResponse, error) {
	out := new(ReadHostResponse)
	err := c.cc.Invoke(ctx, Hosts_Read_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostsClient) Upsert(ctx context.Context, in *UpsertHostRequest, opts ...grpc.CallOption) (*UpsertHostResponse, error) {
	out := new(UpsertHostResponse)
	err := c.cc.Invoke(ctx, Hosts_Upsert_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostsClient) Delete(ctx context.Context, in *DeleteHostRequest, opts ...grpc.CallOption) (*DeleteHostResponse, error) {
	out := new(DeleteHostResponse)
	err := c.cc.Invoke(ctx, Hosts_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostsServer is the server API for Hosts service.
// All implementations must embed UnimplementedHostsServer
// for forward compatibility
type HostsServer interface {
	// General
	Create(context.Context, *CreateHostRequest) (*CreateHostResponse, error)
	Read(context.Context, *ReadHostRequest) (*ReadHostResponse, error)
	Upsert(context.Context, *UpsertHostRequest) (*UpsertHostResponse, error)
	Delete(context.Context, *DeleteHostRequest) (*DeleteHostResponse, error)
	mustEmbedUnimplementedHostsServer()
}

// UnimplementedHostsServer must be embedded to have forward compatible implementations.
type UnimplementedHostsServer struct {
}

func (UnimplementedHostsServer) Create(context.Context, *CreateHostRequest) (*CreateHostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedHostsServer) Read(context.Context, *ReadHostRequest) (*ReadHostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedHostsServer) Upsert(context.Context, *UpsertHostRequest) (*UpsertHostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upsert not implemented")
}
func (UnimplementedHostsServer) Delete(context.Context, *DeleteHostRequest) (*DeleteHostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedHostsServer) mustEmbedUnimplementedHostsServer() {}

// UnsafeHostsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostsServer will
// result in compilation errors.
type UnsafeHostsServer interface {
	mustEmbedUnimplementedHostsServer()
}

func RegisterHostsServer(s grpc.ServiceRegistrar, srv HostsServer) {
	s.RegisterService(&Hosts_ServiceDesc, srv)
}

func _Hosts_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hosts_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostsServer).Create(ctx, req.(*CreateHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hosts_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostsServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hosts_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostsServer).Read(ctx, req.(*ReadHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hosts_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostsServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hosts_Upsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostsServer).Upsert(ctx, req.(*UpsertHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hosts_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hosts_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostsServer).Delete(ctx, req.(*DeleteHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Hosts_ServiceDesc is the grpc.ServiceDesc for Hosts service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hosts_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hosts.Hosts",
	HandlerType: (*HostsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Hosts_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Hosts_Read_Handler,
		},
		{
			MethodName: "Upsert",
			Handler:    _Hosts_Upsert_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Hosts_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "host/pb/rpc/hosts.proto",
}
