// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.18.1
// source: host/pb/rpc/hosts.proto

package rpc

import (
	pb "github.com/d3c3ptive/aims/host/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HostFilters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxResults int64 `protobuf:"varint,1,opt,name=MaxResults,proto3" json:"MaxResults,omitempty"`
	Users      bool  `protobuf:"varint,10,opt,name=Users,proto3" json:"Users,omitempty"`
	// Files: if true and read, loads host files.
	//
	//	if true and write, overwrites any matching file paths.
	Files bool `protobuf:"varint,20,opt,name=Files,proto3" json:"Files,omitempty"`
	// Processes: if true and read, loads host processes.
	//
	//	if true and write, overwrites any matching process IDs.
	Processes      bool `protobuf:"varint,30,opt,name=Processes,proto3" json:"Processes,omitempty"`
	Ports          bool `protobuf:"varint,40,opt,name=Ports,proto3" json:"Ports,omitempty"`
	Trace          bool `protobuf:"varint,41,opt,name=Trace,proto3" json:"Trace,omitempty"`
	Scripts        bool `protobuf:"varint,70,opt,name=Scripts,proto3" json:"Scripts,omitempty"`
	OSFingerprints bool `protobuf:"varint,71,opt,name=OSFingerprints,proto3" json:"OSFingerprints,omitempty"`
}

func (x *HostFilters) Reset() {
	*x = HostFilters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_host_pb_rpc_hosts_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostFilters) ProtoMessage() {}

func (x *HostFilters) ProtoReflect() protoreflect.Message {
	mi := &file_host_pb_rpc_hosts_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostFilters.ProtoReflect.Descriptor instead.
func (*HostFilters) Descriptor() ([]byte, []int) {
	return file_host_pb_rpc_hosts_proto_rawDescGZIP(), []int{0}
}

func (x *HostFilters) GetMaxResults() int64 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

func (x *HostFilters) GetUsers() bool {
	if x != nil {
		return x.Users
	}
	return false
}

func (x *HostFilters) GetFiles() bool {
	if x != nil {
		return x.Files
	}
	return false
}

func (x *HostFilters) GetProcesses() bool {
	if x != nil {
		return x.Processes
	}
	return false
}

func (x *HostFilters) GetPorts() bool {
	if x != nil {
		return x.Ports
	}
	return false
}

func (x *HostFilters) GetTrace() bool {
	if x != nil {
		return x.Trace
	}
	return false
}

func (x *HostFilters) GetScripts() bool {
	if x != nil {
		return x.Scripts
	}
	return false
}

func (x *HostFilters) GetOSFingerprints() bool {
	if x != nil {
		return x.OSFingerprints
	}
	return false
}

type CreateHostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filters *HostFilters `protobuf:"bytes,1,opt,name=Filters,proto3" json:"Filters,omitempty"`
	Hosts   []*pb.Host   `protobuf:"bytes,2,rep,name=Hosts,proto3" json:"Hosts,omitempty"`
}

func (x *CreateHostRequest) Reset() {
	*x = CreateHostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_host_pb_rpc_hosts_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHostRequest) ProtoMessage() {}

func (x *CreateHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_host_pb_rpc_hosts_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHostRequest.ProtoReflect.Descriptor instead.
func (*CreateHostRequest) Descriptor() ([]byte, []int) {
	return file_host_pb_rpc_hosts_proto_rawDescGZIP(), []int{1}
}

func (x *CreateHostRequest) GetFilters() *HostFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *CreateHostRequest) GetHosts() []*pb.Host {
	if x != nil {
		return x.Hosts
	}
	return nil
}

type CreateHostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hosts []*pb.Host `protobuf:"bytes,1,rep,name=Hosts,proto3" json:"Hosts,omitempty"`
}

func (x *CreateHostResponse) Reset() {
	*x = CreateHostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_host_pb_rpc_hosts_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHostResponse) ProtoMessage() {}

func (x *CreateHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_host_pb_rpc_hosts_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHostResponse.ProtoReflect.Descriptor instead.
func (*CreateHostResponse) Descriptor() ([]byte, []int) {
	return file_host_pb_rpc_hosts_proto_rawDescGZIP(), []int{2}
}

func (x *CreateHostResponse) GetHosts() []*pb.Host {
	if x != nil {
		return x.Hosts
	}
	return nil
}

type ReadHostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filters *HostFilters `protobuf:"bytes,1,opt,name=Filters,proto3" json:"Filters,omitempty"`
	Host    *pb.Host     `protobuf:"bytes,2,opt,name=Host,proto3" json:"Host,omitempty"`
}

func (x *ReadHostRequest) Reset() {
	*x = ReadHostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_host_pb_rpc_hosts_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadHostRequest) ProtoMessage() {}

func (x *ReadHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_host_pb_rpc_hosts_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadHostRequest.ProtoReflect.Descriptor instead.
func (*ReadHostRequest) Descriptor() ([]byte, []int) {
	return file_host_pb_rpc_hosts_proto_rawDescGZIP(), []int{3}
}

func (x *ReadHostRequest) GetFilters() *HostFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *ReadHostRequest) GetHost() *pb.Host {
	if x != nil {
		return x.Host
	}
	return nil
}

type ReadHostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hosts []*pb.Host `protobuf:"bytes,1,rep,name=Hosts,proto3" json:"Hosts,omitempty"`
}

func (x *ReadHostResponse) Reset() {
	*x = ReadHostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_host_pb_rpc_hosts_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadHostResponse) ProtoMessage() {}

func (x *ReadHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_host_pb_rpc_hosts_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadHostResponse.ProtoReflect.Descriptor instead.
func (*ReadHostResponse) Descriptor() ([]byte, []int) {
	return file_host_pb_rpc_hosts_proto_rawDescGZIP(), []int{4}
}

func (x *ReadHostResponse) GetHosts() []*pb.Host {
	if x != nil {
		return x.Hosts
	}
	return nil
}

type UpsertHostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filters *HostFilters `protobuf:"bytes,1,opt,name=Filters,proto3" json:"Filters,omitempty"`
	Hosts   []*pb.Host   `protobuf:"bytes,2,rep,name=Hosts,proto3" json:"Hosts,omitempty"`
}

func (x *UpsertHostRequest) Reset() {
	*x = UpsertHostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_host_pb_rpc_hosts_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertHostRequest) ProtoMessage() {}

func (x *UpsertHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_host_pb_rpc_hosts_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertHostRequest.ProtoReflect.Descriptor instead.
func (*UpsertHostRequest) Descriptor() ([]byte, []int) {
	return file_host_pb_rpc_hosts_proto_rawDescGZIP(), []int{5}
}

func (x *UpsertHostRequest) GetFilters() *HostFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *UpsertHostRequest) GetHosts() []*pb.Host {
	if x != nil {
		return x.Hosts
	}
	return nil
}

type UpsertHostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hosts []*pb.Host `protobuf:"bytes,1,rep,name=Hosts,proto3" json:"Hosts,omitempty"`
}

func (x *UpsertHostResponse) Reset() {
	*x = UpsertHostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_host_pb_rpc_hosts_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertHostResponse) ProtoMessage() {}

func (x *UpsertHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_host_pb_rpc_hosts_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertHostResponse.ProtoReflect.Descriptor instead.
func (*UpsertHostResponse) Descriptor() ([]byte, []int) {
	return file_host_pb_rpc_hosts_proto_rawDescGZIP(), []int{6}
}

func (x *UpsertHostResponse) GetHosts() []*pb.Host {
	if x != nil {
		return x.Hosts
	}
	return nil
}

type DeleteHostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hosts []*pb.Host `protobuf:"bytes,1,rep,name=Hosts,proto3" json:"Hosts,omitempty"`
}

func (x *DeleteHostRequest) Reset() {
	*x = DeleteHostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_host_pb_rpc_hosts_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHostRequest) ProtoMessage() {}

func (x *DeleteHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_host_pb_rpc_hosts_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHostRequest.ProtoReflect.Descriptor instead.
func (*DeleteHostRequest) Descriptor() ([]byte, []int) {
	return file_host_pb_rpc_hosts_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteHostRequest) GetHosts() []*pb.Host {
	if x != nil {
		return x.Hosts
	}
	return nil
}

type DeleteHostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hosts []*pb.Host `protobuf:"bytes,1,rep,name=Hosts,proto3" json:"Hosts,omitempty"`
}

func (x *DeleteHostResponse) Reset() {
	*x = DeleteHostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_host_pb_rpc_hosts_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHostResponse) ProtoMessage() {}

func (x *DeleteHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_host_pb_rpc_hosts_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHostResponse.ProtoReflect.Descriptor instead.
func (*DeleteHostResponse) Descriptor() ([]byte, []int) {
	return file_host_pb_rpc_hosts_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteHostResponse) GetHosts() []*pb.Host {
	if x != nil {
		return x.Hosts
	}
	return nil
}

var File_host_pb_rpc_hosts_proto protoreflect.FileDescriptor

var file_host_pb_rpc_hosts_proto_rawDesc = []byte{
	0x0a, 0x17, 0x68, 0x6f, 0x73, 0x74, 0x2f, 0x70, 0x62, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x68, 0x6f,
	0x73, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x68, 0x6f, 0x73, 0x74, 0x73,
	0x1a, 0x12, 0x68, 0x6f, 0x73, 0x74, 0x2f, 0x70, 0x62, 0x2f, 0x68, 0x6f, 0x73, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x68, 0x6f, 0x73, 0x74, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x68, 0x6f, 0x73,
	0x74, 0x2f, 0x70, 0x62, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe5, 0x01, 0x0a, 0x0b, 0x48, 0x6f, 0x73, 0x74, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x4d, 0x61, 0x78, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x4d, 0x61, 0x78, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x55, 0x73, 0x65, 0x72, 0x73, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x46,
	0x69, 0x6c, 0x65, 0x73, 0x18, 0x14, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x46, 0x69, 0x6c, 0x65,
	0x73, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x1e,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x50, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x28, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x50, 0x6f, 0x72, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x72, 0x61, 0x63, 0x65, 0x18, 0x29,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x54, 0x72, 0x61, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x53,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x73, 0x18, 0x46, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x53, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x4f, 0x53, 0x46, 0x69, 0x6e, 0x67, 0x65,
	0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x47, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x4f,
	0x53, 0x46, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x73, 0x22, 0x63, 0x0a,
	0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2c, 0x0a, 0x07, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x2e, 0x48, 0x6f, 0x73, 0x74,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x52, 0x07, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73,
	0x12, 0x20, 0x0a, 0x05, 0x48, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x68, 0x6f, 0x73, 0x74, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x05, 0x48, 0x6f, 0x73,
	0x74, 0x73, 0x22, 0x36, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x05, 0x48, 0x6f, 0x73, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x68, 0x6f, 0x73, 0x74, 0x2e, 0x48,
	0x6f, 0x73, 0x74, 0x52, 0x05, 0x48, 0x6f, 0x73, 0x74, 0x73, 0x22, 0x5f, 0x0a, 0x0f, 0x52, 0x65,
	0x61, 0x64, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a,
	0x07, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x73, 0x52, 0x07, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x12, 0x1e, 0x0a, 0x04, 0x48,
	0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x68, 0x6f, 0x73, 0x74,
	0x2e, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x22, 0x34, 0x0a, 0x10, 0x52,
	0x65, 0x61, 0x64, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x20, 0x0a, 0x05, 0x48, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x68, 0x6f, 0x73, 0x74, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x05, 0x48, 0x6f, 0x73, 0x74,
	0x73, 0x22, 0x63, 0x0a, 0x11, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x07, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x2e,
	0x48, 0x6f, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x52, 0x07, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x73, 0x12, 0x20, 0x0a, 0x05, 0x48, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x68, 0x6f, 0x73, 0x74, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x52,
	0x05, 0x48, 0x6f, 0x73, 0x74, 0x73, 0x22, 0x36, 0x0a, 0x12, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74,
	0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x05,
	0x48, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x68, 0x6f,
	0x73, 0x74, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x05, 0x48, 0x6f, 0x73, 0x74, 0x73, 0x22, 0x35,
	0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x05, 0x48, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x68, 0x6f, 0x73, 0x74, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x05,
	0x48, 0x6f, 0x73, 0x74, 0x73, 0x22, 0x36, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48,
	0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x05, 0x48,
	0x6f, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x68, 0x6f, 0x73,
	0x74, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x05, 0x48, 0x6f, 0x73, 0x74, 0x73, 0x32, 0x85, 0x02,
	0x0a, 0x05, 0x48, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x3f, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x12, 0x18, 0x2e, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x68, 0x6f,
	0x73, 0x74, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x04, 0x52, 0x65, 0x61, 0x64,
	0x12, 0x16, 0x2e, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x48, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x68, 0x6f, 0x73, 0x74, 0x73,
	0x2e, 0x52, 0x65, 0x61, 0x64, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x06, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x12, 0x18, 0x2e,
	0x68, 0x6f, 0x73, 0x74, 0x73, 0x2e, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x48, 0x6f, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x2e,
	0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x18,
	0x2e, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x68, 0x6f, 0x73, 0x74, 0x73,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x72, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x2e, 0x68, 0x6f, 0x73,
	0x74, 0x73, 0x42, 0x0a, 0x48, 0x6f, 0x73, 0x74, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x33, 0x63,
	0x33, 0x70, 0x74, 0x69, 0x76, 0x65, 0x2f, 0x61, 0x69, 0x6d, 0x73, 0x2f, 0x68, 0x6f, 0x73, 0x74,
	0x2f, 0x70, 0x62, 0x2f, 0x72, 0x70, 0x63, 0xa2, 0x02, 0x03, 0x48, 0x58, 0x58, 0xaa, 0x02, 0x05,
	0x48, 0x6f, 0x73, 0x74, 0x73, 0xca, 0x02, 0x05, 0x48, 0x6f, 0x73, 0x74, 0x73, 0xe2, 0x02, 0x11,
	0x48, 0x6f, 0x73, 0x74, 0x73, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0xea, 0x02, 0x05, 0x48, 0x6f, 0x73, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_host_pb_rpc_hosts_proto_rawDescOnce sync.Once
	file_host_pb_rpc_hosts_proto_rawDescData = file_host_pb_rpc_hosts_proto_rawDesc
)

func file_host_pb_rpc_hosts_proto_rawDescGZIP() []byte {
	file_host_pb_rpc_hosts_proto_rawDescOnce.Do(func() {
		file_host_pb_rpc_hosts_proto_rawDescData = protoimpl.X.CompressGZIP(file_host_pb_rpc_hosts_proto_rawDescData)
	})
	return file_host_pb_rpc_hosts_proto_rawDescData
}

var file_host_pb_rpc_hosts_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_host_pb_rpc_hosts_proto_goTypes = []interface{}{
	(*HostFilters)(nil),        // 0: hosts.HostFilters
	(*CreateHostRequest)(nil),  // 1: hosts.CreateHostRequest
	(*CreateHostResponse)(nil), // 2: hosts.CreateHostResponse
	(*ReadHostRequest)(nil),    // 3: hosts.ReadHostRequest
	(*ReadHostResponse)(nil),   // 4: hosts.ReadHostResponse
	(*UpsertHostRequest)(nil),  // 5: hosts.UpsertHostRequest
	(*UpsertHostResponse)(nil), // 6: hosts.UpsertHostResponse
	(*DeleteHostRequest)(nil),  // 7: hosts.DeleteHostRequest
	(*DeleteHostResponse)(nil), // 8: hosts.DeleteHostResponse
	(*pb.Host)(nil),            // 9: host.Host
}
var file_host_pb_rpc_hosts_proto_depIdxs = []int32{
	0,  // 0: hosts.CreateHostRequest.Filters:type_name -> hosts.HostFilters
	9,  // 1: hosts.CreateHostRequest.Hosts:type_name -> host.Host
	9,  // 2: hosts.CreateHostResponse.Hosts:type_name -> host.Host
	0,  // 3: hosts.ReadHostRequest.Filters:type_name -> hosts.HostFilters
	9,  // 4: hosts.ReadHostRequest.Host:type_name -> host.Host
	9,  // 5: hosts.ReadHostResponse.Hosts:type_name -> host.Host
	0,  // 6: hosts.UpsertHostRequest.Filters:type_name -> hosts.HostFilters
	9,  // 7: hosts.UpsertHostRequest.Hosts:type_name -> host.Host
	9,  // 8: hosts.UpsertHostResponse.Hosts:type_name -> host.Host
	9,  // 9: hosts.DeleteHostRequest.Hosts:type_name -> host.Host
	9,  // 10: hosts.DeleteHostResponse.Hosts:type_name -> host.Host
	1,  // 11: hosts.Hosts.Create:input_type -> hosts.CreateHostRequest
	3,  // 12: hosts.Hosts.Read:input_type -> hosts.ReadHostRequest
	5,  // 13: hosts.Hosts.Upsert:input_type -> hosts.UpsertHostRequest
	7,  // 14: hosts.Hosts.Delete:input_type -> hosts.DeleteHostRequest
	2,  // 15: hosts.Hosts.Create:output_type -> hosts.CreateHostResponse
	4,  // 16: hosts.Hosts.Read:output_type -> hosts.ReadHostResponse
	6,  // 17: hosts.Hosts.Upsert:output_type -> hosts.UpsertHostResponse
	8,  // 18: hosts.Hosts.Delete:output_type -> hosts.DeleteHostResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_host_pb_rpc_hosts_proto_init() }
func file_host_pb_rpc_hosts_proto_init() {
	if File_host_pb_rpc_hosts_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_host_pb_rpc_hosts_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostFilters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_host_pb_rpc_hosts_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_host_pb_rpc_hosts_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_host_pb_rpc_hosts_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadHostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_host_pb_rpc_hosts_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadHostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_host_pb_rpc_hosts_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpsertHostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_host_pb_rpc_hosts_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpsertHostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_host_pb_rpc_hosts_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteHostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_host_pb_rpc_hosts_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteHostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_host_pb_rpc_hosts_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_host_pb_rpc_hosts_proto_goTypes,
		DependencyIndexes: file_host_pb_rpc_hosts_proto_depIdxs,
		MessageInfos:      file_host_pb_rpc_hosts_proto_msgTypes,
	}.Build()
	File_host_pb_rpc_hosts_proto = out.File
	file_host_pb_rpc_hosts_proto_rawDesc = nil
	file_host_pb_rpc_hosts_proto_goTypes = nil
	file_host_pb_rpc_hosts_proto_depIdxs = nil
}
