package pb



import (
	"github.com/gofrs/uuid"
	"gorm.io/gorm"
)



// BeforeCreate - GORM-specific autogenerated helpers.
func (sequence *SequenceORM) BeforeCreate(tx *gorm.DB) (err error) {
	// Preserve an explicitly-set primary key: only generate one when none was provided. This
	// lets callers assign a deliberate/shared Id (e.g. one provenance.Source row shared by all
	// the objects a single scan produced) instead of every insert minting a fresh uuid.
	if sequence.Id != "" {
		return nil
	}
    id, err := uuid.NewV4()
	if err != nil {
		return err
	}
    sequence.Id = id.String()

    return nil
}



// BeforeCreate - GORM-specific autogenerated helpers.
func (tcpsequence *TCPSequenceORM) BeforeCreate(tx *gorm.DB) (err error) {
	// Preserve an explicitly-set primary key: only generate one when none was provided. This
	// lets callers assign a deliberate/shared Id (e.g. one provenance.Source row shared by all
	// the objects a single scan produced) instead of every insert minting a fresh uuid.
	if tcpsequence.Id != "" {
		return nil
	}
    id, err := uuid.NewV4()
	if err != nil {
		return err
	}
    tcpsequence.Id = id.String()

    return nil
}



// BeforeCreate - GORM-specific autogenerated helpers.
func (ipidsequence *IPIDSequenceORM) BeforeCreate(tx *gorm.DB) (err error) {
	// Preserve an explicitly-set primary key: only generate one when none was provided. This
	// lets callers assign a deliberate/shared Id (e.g. one provenance.Source row shared by all
	// the objects a single scan produced) instead of every insert minting a fresh uuid.
	if ipidsequence.Id != "" {
		return nil
	}
    id, err := uuid.NewV4()
	if err != nil {
		return err
	}
    ipidsequence.Id = id.String()

    return nil
}



// BeforeCreate - GORM-specific autogenerated helpers.
func (tcptssequence *TCPTSSequenceORM) BeforeCreate(tx *gorm.DB) (err error) {
	// Preserve an explicitly-set primary key: only generate one when none was provided. This
	// lets callers assign a deliberate/shared Id (e.g. one provenance.Source row shared by all
	// the objects a single scan produced) instead of every insert minting a fresh uuid.
	if tcptssequence.Id != "" {
		return nil
	}
    id, err := uuid.NewV4()
	if err != nil {
		return err
	}
    tcptssequence.Id = id.String()

    return nil
}



// BeforeCreate - GORM-specific autogenerated helpers.
func (icmpresponse *ICMPResponseORM) BeforeCreate(tx *gorm.DB) (err error) {
	// Preserve an explicitly-set primary key: only generate one when none was provided. This
	// lets callers assign a deliberate/shared Id (e.g. one provenance.Source row shared by all
	// the objects a single scan produced) instead of every insert minting a fresh uuid.
	if icmpresponse.Id != "" {
		return nil
	}
    id, err := uuid.NewV4()
	if err != nil {
		return err
	}
    icmpresponse.Id = id.String()

    return nil
}



