package host



import (
	"github.com/gofrs/uuid"
	"gorm.io/gorm"
)



// BeforeCreate - GORM-specific autogenerated helpers.
func (port *PortORM) BeforeCreate(tx *gorm.DB) (err error) {
    id, err := uuid.NewV4()
	if err != nil {
		return err
	}
    port.Id = id.String()

    return nil
}



// BeforeCreate - GORM-specific autogenerated helpers.
func (reason *ReasonORM) BeforeCreate(tx *gorm.DB) (err error) {
    id, err := uuid.NewV4()
	if err != nil {
		return err
	}
    reason.Id = id.String()

    return nil
}



// BeforeCreate - GORM-specific autogenerated helpers.
func (extraport *ExtraPortORM) BeforeCreate(tx *gorm.DB) (err error) {
    id, err := uuid.NewV4()
	if err != nil {
		return err
	}
    extraport.Id = id.String()

    return nil
}



// BeforeCreate - GORM-specific autogenerated helpers.
func (state *StateORM) BeforeCreate(tx *gorm.DB) (err error) {
    id, err := uuid.NewV4()
	if err != nil {
		return err
	}
    state.Id = id.String()

    return nil
}



