// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.15.8
// source: scan/pb/rpc/scans.proto

package rpc

import (
	pb1 "github.com/d3c3ptive/aims/host/pb"
	pb "github.com/d3c3ptive/aims/scan/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunFilters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxResults int64 `protobuf:"varint,1,opt,name=MaxResults,proto3" json:"MaxResults,omitempty"`
	Hosts      bool  `protobuf:"varint,2,opt,name=Hosts,proto3" json:"Hosts,omitempty"`
	Ports      bool  `protobuf:"varint,3,opt,name=Ports,proto3" json:"Ports,omitempty"`
	// Source: if set, scope the read to only the runs of this tool (matched against the
	// run's Scanner, which is the producing tool). Empty means all runs.
	Source string `protobuf:"bytes,4,opt,name=Source,proto3" json:"Source,omitempty"`
}

func (x *RunFilters) Reset() {
	*x = RunFilters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_pb_rpc_scans_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunFilters) ProtoMessage() {}

func (x *RunFilters) ProtoReflect() protoreflect.Message {
	mi := &file_scan_pb_rpc_scans_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunFilters.ProtoReflect.Descriptor instead.
func (*RunFilters) Descriptor() ([]byte, []int) {
	return file_scan_pb_rpc_scans_proto_rawDescGZIP(), []int{0}
}

func (x *RunFilters) GetMaxResults() int64 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

func (x *RunFilters) GetHosts() bool {
	if x != nil {
		return x.Hosts
	}
	return false
}

func (x *RunFilters) GetPorts() bool {
	if x != nil {
		return x.Ports
	}
	return false
}

func (x *RunFilters) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type CreateScanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filters *RunFilters `protobuf:"bytes,1,opt,name=Filters,proto3" json:"Filters,omitempty"`
	Scans   []*pb.Run   `protobuf:"bytes,2,rep,name=Scans,proto3" json:"Scans,omitempty"`
}

func (x *CreateScanRequest) Reset() {
	*x = CreateScanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_pb_rpc_scans_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScanRequest) ProtoMessage() {}

func (x *CreateScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scan_pb_rpc_scans_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScanRequest.ProtoReflect.Descriptor instead.
func (*CreateScanRequest) Descriptor() ([]byte, []int) {
	return file_scan_pb_rpc_scans_proto_rawDescGZIP(), []int{1}
}

func (x *CreateScanRequest) GetFilters() *RunFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *CreateScanRequest) GetScans() []*pb.Run {
	if x != nil {
		return x.Scans
	}
	return nil
}

type CreateScanResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scans []*pb.Run `protobuf:"bytes,1,rep,name=Scans,proto3" json:"Scans,omitempty"`
}

func (x *CreateScanResponse) Reset() {
	*x = CreateScanResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_pb_rpc_scans_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScanResponse) ProtoMessage() {}

func (x *CreateScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scan_pb_rpc_scans_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScanResponse.ProtoReflect.Descriptor instead.
func (*CreateScanResponse) Descriptor() ([]byte, []int) {
	return file_scan_pb_rpc_scans_proto_rawDescGZIP(), []int{2}
}

func (x *CreateScanResponse) GetScans() []*pb.Run {
	if x != nil {
		return x.Scans
	}
	return nil
}

type ReadScanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filters *RunFilters `protobuf:"bytes,1,opt,name=Filters,proto3" json:"Filters,omitempty"`
	Scan    *pb.Run     `protobuf:"bytes,2,opt,name=Scan,proto3" json:"Scan,omitempty"`
}

func (x *ReadScanRequest) Reset() {
	*x = ReadScanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_pb_rpc_scans_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadScanRequest) ProtoMessage() {}

func (x *ReadScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scan_pb_rpc_scans_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadScanRequest.ProtoReflect.Descriptor instead.
func (*ReadScanRequest) Descriptor() ([]byte, []int) {
	return file_scan_pb_rpc_scans_proto_rawDescGZIP(), []int{3}
}

func (x *ReadScanRequest) GetFilters() *RunFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *ReadScanRequest) GetScan() *pb.Run {
	if x != nil {
		return x.Scan
	}
	return nil
}

type ReadScanResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scans []*pb.Run `protobuf:"bytes,1,rep,name=Scans,proto3" json:"Scans,omitempty"`
}

func (x *ReadScanResponse) Reset() {
	*x = ReadScanResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_pb_rpc_scans_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadScanResponse) ProtoMessage() {}

func (x *ReadScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scan_pb_rpc_scans_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadScanResponse.ProtoReflect.Descriptor instead.
func (*ReadScanResponse) Descriptor() ([]byte, []int) {
	return file_scan_pb_rpc_scans_proto_rawDescGZIP(), []int{4}
}

func (x *ReadScanResponse) GetScans() []*pb.Run {
	if x != nil {
		return x.Scans
	}
	return nil
}

type ReadScanManyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filters *RunFilters `protobuf:"bytes,1,opt,name=Filters,proto3" json:"Filters,omitempty"`
	Scan    *pb.Run     `protobuf:"bytes,2,opt,name=Scan,proto3" json:"Scan,omitempty"`
}

func (x *ReadScanManyRequest) Reset() {
	*x = ReadScanManyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_pb_rpc_scans_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadScanManyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadScanManyRequest) ProtoMessage() {}

func (x *ReadScanManyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scan_pb_rpc_scans_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadScanManyRequest.ProtoReflect.Descriptor instead.
func (*ReadScanManyRequest) Descriptor() ([]byte, []int) {
	return file_scan_pb_rpc_scans_proto_rawDescGZIP(), []int{5}
}

func (x *ReadScanManyRequest) GetFilters() *RunFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *ReadScanManyRequest) GetScan() *pb.Run {
	if x != nil {
		return x.Scan
	}
	return nil
}

type ReadScanManyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scans []*pb.Run `protobuf:"bytes,1,rep,name=Scans,proto3" json:"Scans,omitempty"`
}

func (x *ReadScanManyResponse) Reset() {
	*x = ReadScanManyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_pb_rpc_scans_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadScanManyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadScanManyResponse) ProtoMessage() {}

func (x *ReadScanManyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scan_pb_rpc_scans_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadScanManyResponse.ProtoReflect.Descriptor instead.
func (*ReadScanManyResponse) Descriptor() ([]byte, []int) {
	return file_scan_pb_rpc_scans_proto_rawDescGZIP(), []int{6}
}

func (x *ReadScanManyResponse) GetScans() []*pb.Run {
	if x != nil {
		return x.Scans
	}
	return nil
}

type UpsertScanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scans []*pb.Run `protobuf:"bytes,1,rep,name=Scans,proto3" json:"Scans,omitempty"`
}

func (x *UpsertScanRequest) Reset() {
	*x = UpsertScanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_pb_rpc_scans_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertScanRequest) ProtoMessage() {}

func (x *UpsertScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scan_pb_rpc_scans_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertScanRequest.ProtoReflect.Descriptor instead.
func (*UpsertScanRequest) Descriptor() ([]byte, []int) {
	return file_scan_pb_rpc_scans_proto_rawDescGZIP(), []int{7}
}

func (x *UpsertScanRequest) GetScans() []*pb.Run {
	if x != nil {
		return x.Scans
	}
	return nil
}

type UpsertScanResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scans []*pb.Run `protobuf:"bytes,1,rep,name=Scans,proto3" json:"Scans,omitempty"`
}

func (x *UpsertScanResponse) Reset() {
	*x = UpsertScanResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_pb_rpc_scans_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertScanResponse) ProtoMessage() {}

func (x *UpsertScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scan_pb_rpc_scans_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertScanResponse.ProtoReflect.Descriptor instead.
func (*UpsertScanResponse) Descriptor() ([]byte, []int) {
	return file_scan_pb_rpc_scans_proto_rawDescGZIP(), []int{8}
}

func (x *UpsertScanResponse) GetScans() []*pb.Run {
	if x != nil {
		return x.Scans
	}
	return nil
}

type DeleteScanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scans []*pb.Run `protobuf:"bytes,1,rep,name=Scans,proto3" json:"Scans,omitempty"`
}

func (x *DeleteScanRequest) Reset() {
	*x = DeleteScanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_pb_rpc_scans_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScanRequest) ProtoMessage() {}

func (x *DeleteScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scan_pb_rpc_scans_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScanRequest.ProtoReflect.Descriptor instead.
func (*DeleteScanRequest) Descriptor() ([]byte, []int) {
	return file_scan_pb_rpc_scans_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteScanRequest) GetScans() []*pb.Run {
	if x != nil {
		return x.Scans
	}
	return nil
}

type DeleteScanResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scans []*pb.Run `protobuf:"bytes,1,rep,name=Scans,proto3" json:"Scans,omitempty"`
}

func (x *DeleteScanResponse) Reset() {
	*x = DeleteScanResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_pb_rpc_scans_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScanResponse) ProtoMessage() {}

func (x *DeleteScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scan_pb_rpc_scans_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScanResponse.ProtoReflect.Descriptor instead.
func (*DeleteScanResponse) Descriptor() ([]byte, []int) {
	return file_scan_pb_rpc_scans_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteScanResponse) GetScans() []*pb.Run {
	if x != nil {
		return x.Scans
	}
	return nil
}

// RunScanRequest asks the server to run a scanner against targets (and/or raw args).
type RunScanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Scanner is the tool to drive (e.g. "nmap"); it names a server-side Scanner adapter.
	Scanner string `protobuf:"bytes,1,opt,name=Scanner,proto3" json:"Scanner,omitempty"`
	// Args are extra tool arguments (raw passthrough), placed before the target specs.
	Args []string `protobuf:"bytes,2,rep,name=Args,proto3" json:"Args,omitempty"`
	// Targets are the scan targets (typically derived from stored hosts).
	Targets []*pb.Target `protobuf:"bytes,3,rep,name=Targets,proto3" json:"Targets,omitempty"`
	// Background detaches the job: the server returns the JobId frame and keeps running.
	Background bool `protobuf:"varint,4,opt,name=Background,proto3" json:"Background,omitempty"`
}

func (x *RunScanRequest) Reset() {
	*x = RunScanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_pb_rpc_scans_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunScanRequest) ProtoMessage() {}

func (x *RunScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scan_pb_rpc_scans_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunScanRequest.ProtoReflect.Descriptor instead.
func (*RunScanRequest) Descriptor() ([]byte, []int) {
	return file_scan_pb_rpc_scans_proto_rawDescGZIP(), []int{11}
}

func (x *RunScanRequest) GetScanner() string {
	if x != nil {
		return x.Scanner
	}
	return ""
}

func (x *RunScanRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *RunScanRequest) GetTargets() []*pb.Target {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *RunScanRequest) GetBackground() bool {
	if x != nil {
		return x.Background
	}
	return false
}

// RunUpdate is one frame of a running scan's stream: exactly one of the fields is set.
type RunUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Update:
	//
	//	*RunUpdate_JobId
	//	*RunUpdate_Progress
	//	*RunUpdate_Host
	//	*RunUpdate_Final
	//	*RunUpdate_Error
	Update isRunUpdate_Update `protobuf_oneof:"update"`
}

func (x *RunUpdate) Reset() {
	*x = RunUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_pb_rpc_scans_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunUpdate) ProtoMessage() {}

func (x *RunUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_scan_pb_rpc_scans_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunUpdate.ProtoReflect.Descriptor instead.
func (*RunUpdate) Descriptor() ([]byte, []int) {
	return file_scan_pb_rpc_scans_proto_rawDescGZIP(), []int{12}
}

func (m *RunUpdate) GetUpdate() isRunUpdate_Update {
	if m != nil {
		return m.Update
	}
	return nil
}

func (x *RunUpdate) GetJobId() string {
	if x, ok := x.GetUpdate().(*RunUpdate_JobId); ok {
		return x.JobId
	}
	return ""
}

func (x *RunUpdate) GetProgress() *pb.TaskProgress {
	if x, ok := x.GetUpdate().(*RunUpdate_Progress); ok {
		return x.Progress
	}
	return nil
}

func (x *RunUpdate) GetHost() *pb1.Host {
	if x, ok := x.GetUpdate().(*RunUpdate_Host); ok {
		return x.Host
	}
	return nil
}

func (x *RunUpdate) GetFinal() *pb.Run {
	if x, ok := x.GetUpdate().(*RunUpdate_Final); ok {
		return x.Final
	}
	return nil
}

func (x *RunUpdate) GetError() string {
	if x, ok := x.GetUpdate().(*RunUpdate_Error); ok {
		return x.Error
	}
	return ""
}

type isRunUpdate_Update interface {
	isRunUpdate_Update()
}

type RunUpdate_JobId struct {
	// JobId identifies the server-side job; sent as the first frame.
	JobId string `protobuf:"bytes,1,opt,name=JobId,proto3,oneof"`
}

type RunUpdate_Progress struct {
	// Progress is a taskprogress frame from the scanner.
	Progress *pb.TaskProgress `protobuf:"bytes,2,opt,name=Progress,proto3,oneof"`
}

type RunUpdate_Host struct {
	// Host is a host the scan has finished, streamed as it is found.
	Host *pb1.Host `protobuf:"bytes,3,opt,name=Host,proto3,oneof"`
}

type RunUpdate_Final struct {
	// Final is the completed, stored run; sent as the last frame of a foreground stream.
	Final *pb.Run `protobuf:"bytes,4,opt,name=Final,proto3,oneof"`
}

type RunUpdate_Error struct {
	// Error carries a fatal scan error (the stream ends after it).
	Error string `protobuf:"bytes,5,opt,name=Error,proto3,oneof"`
}

func (*RunUpdate_JobId) isRunUpdate_Update() {}

func (*RunUpdate_Progress) isRunUpdate_Update() {}

func (*RunUpdate_Host) isRunUpdate_Update() {}

func (*RunUpdate_Final) isRunUpdate_Update() {}

func (*RunUpdate_Error) isRunUpdate_Update() {}

type JobsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *JobsRequest) Reset() {
	*x = JobsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_pb_rpc_scans_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobsRequest) ProtoMessage() {}

func (x *JobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scan_pb_rpc_scans_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobsRequest.ProtoReflect.Descriptor instead.
func (*JobsRequest) Descriptor() ([]byte, []int) {
	return file_scan_pb_rpc_scans_proto_rawDescGZIP(), []int{13}
}

// ScanJob describes one running server-side scan.
type ScanJob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string       `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Scanner   string       `protobuf:"bytes,2,opt,name=Scanner,proto3" json:"Scanner,omitempty"`
	Args      []string     `protobuf:"bytes,3,rep,name=Args,proto3" json:"Args,omitempty"`
	StartedAt int64        `protobuf:"varint,4,opt,name=StartedAt,proto3" json:"StartedAt,omitempty"`
	Targets   []*pb.Target `protobuf:"bytes,5,rep,name=Targets,proto3" json:"Targets,omitempty"`
}

func (x *ScanJob) Reset() {
	*x = ScanJob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_pb_rpc_scans_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanJob) ProtoMessage() {}

func (x *ScanJob) ProtoReflect() protoreflect.Message {
	mi := &file_scan_pb_rpc_scans_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanJob.ProtoReflect.Descriptor instead.
func (*ScanJob) Descriptor() ([]byte, []int) {
	return file_scan_pb_rpc_scans_proto_rawDescGZIP(), []int{14}
}

func (x *ScanJob) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScanJob) GetScanner() string {
	if x != nil {
		return x.Scanner
	}
	return ""
}

func (x *ScanJob) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ScanJob) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *ScanJob) GetTargets() []*pb.Target {
	if x != nil {
		return x.Targets
	}
	return nil
}

type JobsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jobs []*ScanJob `protobuf:"bytes,1,rep,name=Jobs,proto3" json:"Jobs,omitempty"`
}

func (x *JobsResponse) Reset() {
	*x = JobsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_pb_rpc_scans_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobsResponse) ProtoMessage() {}

func (x *JobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scan_pb_rpc_scans_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobsResponse.ProtoReflect.Descriptor instead.
func (*JobsResponse) Descriptor() ([]byte, []int) {
	return file_scan_pb_rpc_scans_proto_rawDescGZIP(), []int{15}
}

func (x *JobsResponse) GetJobs() []*ScanJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type AttachRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId string `protobuf:"bytes,1,opt,name=JobId,proto3" json:"JobId,omitempty"`
}

func (x *AttachRequest) Reset() {
	*x = AttachRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_pb_rpc_scans_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttachRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachRequest) ProtoMessage() {}

func (x *AttachRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scan_pb_rpc_scans_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachRequest.ProtoReflect.Descriptor instead.
func (*AttachRequest) Descriptor() ([]byte, []int) {
	return file_scan_pb_rpc_scans_proto_rawDescGZIP(), []int{16}
}

func (x *AttachRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type StopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId string `protobuf:"bytes,1,opt,name=JobId,proto3" json:"JobId,omitempty"`
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_pb_rpc_scans_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scan_pb_rpc_scans_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_scan_pb_rpc_scans_proto_rawDescGZIP(), []int{17}
}

func (x *StopRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type StopResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId   string `protobuf:"bytes,1,opt,name=JobId,proto3" json:"JobId,omitempty"`
	Stopped bool   `protobuf:"varint,2,opt,name=Stopped,proto3" json:"Stopped,omitempty"`
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan_pb_rpc_scans_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scan_pb_rpc_scans_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_scan_pb_rpc_scans_proto_rawDescGZIP(), []int{18}
}

func (x *StopResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *StopResponse) GetStopped() bool {
	if x != nil {
		return x.Stopped
	}
	return false
}

var File_scan_pb_rpc_scans_proto protoreflect.FileDescriptor

var file_scan_pb_rpc_scans_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x63, 0x61, 0x6e, 0x2f, 0x70, 0x62, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x63,
	0x61, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x63, 0x61, 0x6e, 0x73,
	0x1a, 0x12, 0x73, 0x63, 0x61, 0x6e, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x68, 0x6f, 0x73, 0x74, 0x2f, 0x70, 0x62, 0x2f, 0x68, 0x6f,
	0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x70, 0x0a, 0x0a, 0x52, 0x75, 0x6e, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x4d, 0x61, 0x78, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x4d, 0x61, 0x78, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x48, 0x6f, 0x73, 0x74, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x48, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x50, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x50, 0x6f, 0x72,
	0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x61, 0x0a, 0x11, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x2b, 0x0a, 0x07, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x73, 0x2e, 0x52, 0x75, 0x6e, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x73, 0x52, 0x07, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x12, 0x1f, 0x0a, 0x05,
	0x53, 0x63, 0x61, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x73, 0x63,
	0x61, 0x6e, 0x2e, 0x52, 0x75, 0x6e, 0x52, 0x05, 0x53, 0x63, 0x61, 0x6e, 0x73, 0x22, 0x35, 0x0a,
	0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x05, 0x53, 0x63, 0x61, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x52, 0x75, 0x6e, 0x52, 0x05, 0x53,
	0x63, 0x61, 0x6e, 0x73, 0x22, 0x5d, 0x0a, 0x0f, 0x52, 0x65, 0x61, 0x64, 0x53, 0x63, 0x61, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x07, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x73,
	0x2e, 0x52, 0x75, 0x6e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x52, 0x07, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x73, 0x12, 0x1d, 0x0a, 0x04, 0x53, 0x63, 0x61, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x52, 0x75, 0x6e, 0x52, 0x04, 0x53,
	0x63, 0x61, 0x6e, 0x22, 0x33, 0x0a, 0x10, 0x52, 0x65, 0x61, 0x64, 0x53, 0x63, 0x61, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x05, 0x53, 0x63, 0x61, 0x6e, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x52, 0x75,
	0x6e, 0x52, 0x05, 0x53, 0x63, 0x61, 0x6e, 0x73, 0x22, 0x61, 0x0a, 0x13, 0x52, 0x65, 0x61, 0x64,
	0x53, 0x63, 0x61, 0x6e, 0x4d, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x2b, 0x0a, 0x07, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x73, 0x2e, 0x52, 0x75, 0x6e, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x73, 0x52, 0x07, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x12, 0x1d, 0x0a, 0x04,
	0x53, 0x63, 0x61, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x73, 0x63, 0x61,
	0x6e, 0x2e, 0x52, 0x75, 0x6e, 0x52, 0x04, 0x53, 0x63, 0x61, 0x6e, 0x22, 0x37, 0x0a, 0x14, 0x52,
	0x65, 0x61, 0x64, 0x53, 0x63, 0x61, 0x6e, 0x4d, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x05, 0x53, 0x63, 0x61, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x52, 0x75, 0x6e, 0x52, 0x05, 0x53,
	0x63, 0x61, 0x6e, 0x73, 0x22, 0x34, 0x0a, 0x11, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x53, 0x63,
	0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x05, 0x53, 0x63, 0x61,
	0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x2e,
	0x52, 0x75, 0x6e, 0x52, 0x05, 0x53, 0x63, 0x61, 0x6e, 0x73, 0x22, 0x35, 0x0a, 0x12, 0x55, 0x70,
	0x73, 0x65, 0x72, 0x74, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1f, 0x0a, 0x05, 0x53, 0x63, 0x61, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x52, 0x75, 0x6e, 0x52, 0x05, 0x53, 0x63, 0x61, 0x6e,
	0x73, 0x22, 0x34, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x63, 0x61, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x05, 0x53, 0x63, 0x61, 0x6e, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x52, 0x75, 0x6e,
	0x52, 0x05, 0x53, 0x63, 0x61, 0x6e, 0x73, 0x22, 0x35, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a,
	0x05, 0x53, 0x63, 0x61, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x73,
	0x63, 0x61, 0x6e, 0x2e, 0x52, 0x75, 0x6e, 0x52, 0x05, 0x53, 0x63, 0x61, 0x6e, 0x73, 0x22, 0x86,
	0x01, 0x0a, 0x0e, 0x52, 0x75, 0x6e, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x41,
	0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x41, 0x72, 0x67, 0x73, 0x12,
	0x26, 0x0a, 0x07, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x07,
	0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x42, 0x61, 0x63, 0x6b, 0x67,
	0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x42, 0x61, 0x63,
	0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x22, 0xbc, 0x01, 0x0a, 0x09, 0x52, 0x75, 0x6e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x05, 0x4a, 0x6f, 0x62, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x4a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x30, 0x0a,
	0x08, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x50, 0x72, 0x6f, 0x67, 0x72,
	0x65, 0x73, 0x73, 0x48, 0x00, 0x52, 0x08, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x20, 0x0a, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x68, 0x6f, 0x73, 0x74, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x48, 0x00, 0x52, 0x04, 0x48, 0x6f, 0x73,
	0x74, 0x12, 0x21, 0x0a, 0x05, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x52, 0x75, 0x6e, 0x48, 0x00, 0x52, 0x05, 0x46,
	0x69, 0x6e, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x08, 0x0a, 0x06,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x0d, 0x0a, 0x0b, 0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x8d, 0x01, 0x0a, 0x07, 0x53, 0x63, 0x61, 0x6e, 0x4a, 0x6f,
	0x62, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x41,
	0x72, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x41, 0x72, 0x67, 0x73, 0x12,
	0x1c, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x26, 0x0a,
	0x07, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x07, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x73, 0x22, 0x32, 0x0a, 0x0c, 0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x4a, 0x6f, 0x62, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x73, 0x2e, 0x53, 0x63, 0x61, 0x6e,
	0x4a, 0x6f, 0x62, 0x52, 0x04, 0x4a, 0x6f, 0x62, 0x73, 0x22, 0x25, 0x0a, 0x0d, 0x41, 0x74, 0x74,
	0x61, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x4a, 0x6f,
	0x62, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4a, 0x6f, 0x62, 0x49, 0x64,
	0x22, 0x23, 0x0a, 0x0b, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x4a, 0x6f, 0x62, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x4a, 0x6f, 0x62, 0x49, 0x64, 0x22, 0x3e, 0x0a, 0x0c, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4a, 0x6f, 0x62, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x53,
	0x74, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x53, 0x74,
	0x6f, 0x70, 0x70, 0x65, 0x64, 0x32, 0x90, 0x04, 0x0a, 0x05, 0x53, 0x63, 0x61, 0x6e, 0x73, 0x12,
	0x3f, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x18, 0x2e, 0x73, 0x63, 0x61, 0x6e,
	0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x39, 0x0a, 0x04, 0x52, 0x65, 0x61, 0x64, 0x12, 0x16, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x73,
	0x2e, 0x52, 0x65, 0x61, 0x64, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x17, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x73, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x53, 0x63, 0x61,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x04, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x16, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x73, 0x2e, 0x52, 0x65, 0x61, 0x64,
	0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x73, 0x63,
	0x61, 0x6e, 0x73, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x06, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74,
	0x12, 0x18, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x73, 0x2e, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x53,
	0x63, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x73, 0x63, 0x61,
	0x6e, 0x73, 0x2e, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x12, 0x18, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x73, 0x63,
	0x61, 0x6e, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x03, 0x52, 0x75, 0x6e, 0x12,
	0x15, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x73, 0x2e, 0x52, 0x75, 0x6e, 0x53, 0x63, 0x61, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x73, 0x2e, 0x52,
	0x75, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x31, 0x0a, 0x04,
	0x4a, 0x6f, 0x62, 0x73, 0x12, 0x12, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x73, 0x2e, 0x4a, 0x6f, 0x62,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x73,
	0x2e, 0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x34, 0x0a, 0x06, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x12, 0x14, 0x2e, 0x73, 0x63, 0x61, 0x6e,
	0x73, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x10, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x73, 0x2e, 0x52, 0x75, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x31, 0x0a, 0x04, 0x53, 0x74, 0x6f, 0x70, 0x12, 0x12, 0x2e,
	0x73, 0x63, 0x61, 0x6e, 0x73, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x13, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x73, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_scan_pb_rpc_scans_proto_rawDescOnce sync.Once
	file_scan_pb_rpc_scans_proto_rawDescData = file_scan_pb_rpc_scans_proto_rawDesc
)

func file_scan_pb_rpc_scans_proto_rawDescGZIP() []byte {
	file_scan_pb_rpc_scans_proto_rawDescOnce.Do(func() {
		file_scan_pb_rpc_scans_proto_rawDescData = protoimpl.X.CompressGZIP(file_scan_pb_rpc_scans_proto_rawDescData)
	})
	return file_scan_pb_rpc_scans_proto_rawDescData
}

var file_scan_pb_rpc_scans_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_scan_pb_rpc_scans_proto_goTypes = []interface{}{
	(*RunFilters)(nil),           // 0: scans.RunFilters
	(*CreateScanRequest)(nil),    // 1: scans.CreateScanRequest
	(*CreateScanResponse)(nil),   // 2: scans.CreateScanResponse
	(*ReadScanRequest)(nil),      // 3: scans.ReadScanRequest
	(*ReadScanResponse)(nil),     // 4: scans.ReadScanResponse
	(*ReadScanManyRequest)(nil),  // 5: scans.ReadScanManyRequest
	(*ReadScanManyResponse)(nil), // 6: scans.ReadScanManyResponse
	(*UpsertScanRequest)(nil),    // 7: scans.UpsertScanRequest
	(*UpsertScanResponse)(nil),   // 8: scans.UpsertScanResponse
	(*DeleteScanRequest)(nil),    // 9: scans.DeleteScanRequest
	(*DeleteScanResponse)(nil),   // 10: scans.DeleteScanResponse
	(*RunScanRequest)(nil),       // 11: scans.RunScanRequest
	(*RunUpdate)(nil),            // 12: scans.RunUpdate
	(*JobsRequest)(nil),          // 13: scans.JobsRequest
	(*ScanJob)(nil),              // 14: scans.ScanJob
	(*JobsResponse)(nil),         // 15: scans.JobsResponse
	(*AttachRequest)(nil),        // 16: scans.AttachRequest
	(*StopRequest)(nil),          // 17: scans.StopRequest
	(*StopResponse)(nil),         // 18: scans.StopResponse
	(*pb.Run)(nil),               // 19: scan.Run
	(*pb.Target)(nil),            // 20: scan.Target
	(*pb.TaskProgress)(nil),      // 21: scan.TaskProgress
	(*pb1.Host)(nil),             // 22: host.Host
}
var file_scan_pb_rpc_scans_proto_depIdxs = []int32{
	0,  // 0: scans.CreateScanRequest.Filters:type_name -> scans.RunFilters
	19, // 1: scans.CreateScanRequest.Scans:type_name -> scan.Run
	19, // 2: scans.CreateScanResponse.Scans:type_name -> scan.Run
	0,  // 3: scans.ReadScanRequest.Filters:type_name -> scans.RunFilters
	19, // 4: scans.ReadScanRequest.Scan:type_name -> scan.Run
	19, // 5: scans.ReadScanResponse.Scans:type_name -> scan.Run
	0,  // 6: scans.ReadScanManyRequest.Filters:type_name -> scans.RunFilters
	19, // 7: scans.ReadScanManyRequest.Scan:type_name -> scan.Run
	19, // 8: scans.ReadScanManyResponse.Scans:type_name -> scan.Run
	19, // 9: scans.UpsertScanRequest.Scans:type_name -> scan.Run
	19, // 10: scans.UpsertScanResponse.Scans:type_name -> scan.Run
	19, // 11: scans.DeleteScanRequest.Scans:type_name -> scan.Run
	19, // 12: scans.DeleteScanResponse.Scans:type_name -> scan.Run
	20, // 13: scans.RunScanRequest.Targets:type_name -> scan.Target
	21, // 14: scans.RunUpdate.Progress:type_name -> scan.TaskProgress
	22, // 15: scans.RunUpdate.Host:type_name -> host.Host
	19, // 16: scans.RunUpdate.Final:type_name -> scan.Run
	20, // 17: scans.ScanJob.Targets:type_name -> scan.Target
	14, // 18: scans.JobsResponse.Jobs:type_name -> scans.ScanJob
	1,  // 19: scans.Scans.Create:input_type -> scans.CreateScanRequest
	3,  // 20: scans.Scans.Read:input_type -> scans.ReadScanRequest
	3,  // 21: scans.Scans.List:input_type -> scans.ReadScanRequest
	7,  // 22: scans.Scans.Upsert:input_type -> scans.UpsertScanRequest
	9,  // 23: scans.Scans.Delete:input_type -> scans.DeleteScanRequest
	11, // 24: scans.Scans.Run:input_type -> scans.RunScanRequest
	13, // 25: scans.Scans.Jobs:input_type -> scans.JobsRequest
	16, // 26: scans.Scans.Attach:input_type -> scans.AttachRequest
	17, // 27: scans.Scans.Stop:input_type -> scans.StopRequest
	2,  // 28: scans.Scans.Create:output_type -> scans.CreateScanResponse
	4,  // 29: scans.Scans.Read:output_type -> scans.ReadScanResponse
	4,  // 30: scans.Scans.List:output_type -> scans.ReadScanResponse
	8,  // 31: scans.Scans.Upsert:output_type -> scans.UpsertScanResponse
	10, // 32: scans.Scans.Delete:output_type -> scans.DeleteScanResponse
	12, // 33: scans.Scans.Run:output_type -> scans.RunUpdate
	15, // 34: scans.Scans.Jobs:output_type -> scans.JobsResponse
	12, // 35: scans.Scans.Attach:output_type -> scans.RunUpdate
	18, // 36: scans.Scans.Stop:output_type -> scans.StopResponse
	28, // [28:37] is the sub-list for method output_type
	19, // [19:28] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_scan_pb_rpc_scans_proto_init() }
func file_scan_pb_rpc_scans_proto_init() {
	if File_scan_pb_rpc_scans_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_scan_pb_rpc_scans_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunFilters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_pb_rpc_scans_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateScanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_pb_rpc_scans_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateScanResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_pb_rpc_scans_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadScanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_pb_rpc_scans_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadScanResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_pb_rpc_scans_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadScanManyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_pb_rpc_scans_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadScanManyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_pb_rpc_scans_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpsertScanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_pb_rpc_scans_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpsertScanResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_pb_rpc_scans_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteScanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_pb_rpc_scans_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteScanResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_pb_rpc_scans_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunScanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_pb_rpc_scans_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_pb_rpc_scans_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_pb_rpc_scans_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanJob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_pb_rpc_scans_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_pb_rpc_scans_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttachRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_pb_rpc_scans_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan_pb_rpc_scans_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_scan_pb_rpc_scans_proto_msgTypes[12].OneofWrappers = []interface{}{
		(*RunUpdate_JobId)(nil),
		(*RunUpdate_Progress)(nil),
		(*RunUpdate_Host)(nil),
		(*RunUpdate_Final)(nil),
		(*RunUpdate_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_scan_pb_rpc_scans_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scan_pb_rpc_scans_proto_goTypes,
		DependencyIndexes: file_scan_pb_rpc_scans_proto_depIdxs,
		MessageInfos:      file_scan_pb_rpc_scans_proto_msgTypes,
	}.Build()
	File_scan_pb_rpc_scans_proto = out.File
	file_scan_pb_rpc_scans_proto_rawDesc = nil
	file_scan_pb_rpc_scans_proto_goTypes = nil
	file_scan_pb_rpc_scans_proto_depIdxs = nil
}
