// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.18.1
// source: credential/pb/rpc/logins.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Logins_Create_FullMethodName = "/credentials.Logins/Create"
	Logins_Read_FullMethodName   = "/credentials.Logins/Read"
	Logins_List_FullMethodName   = "/credentials.Logins/List"
	Logins_Upsert_FullMethodName = "/credentials.Logins/Upsert"
	Logins_Delete_FullMethodName = "/credentials.Logins/Delete"
)

// LoginsClient is the client API for Logins service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoginsClient interface {
	Create(ctx context.Context, in *CreateLoginRequest, opts ...grpc.CallOption) (*CreateLoginResponse, error)
	Read(ctx context.Context, in *ReadLoginRequest, opts ...grpc.CallOption) (*ReadLoginResponse, error)
	List(ctx context.Context, in *ReadLoginRequest, opts ...grpc.CallOption) (*ReadLoginResponse, error)
	Upsert(ctx context.Context, in *UpsertLoginRequest, opts ...grpc.CallOption) (*UpsertLoginResponse, error)
	Delete(ctx context.Context, in *DeleteLoginRequest, opts ...grpc.CallOption) (*DeleteLoginResponse, error)
}

type loginsClient struct {
	cc grpc.ClientConnInterface
}

func NewLoginsClient(cc grpc.ClientConnInterface) LoginsClient {
	return &loginsClient{cc}
}

func (c *loginsClient) Create(ctx context.Context, in *CreateLoginRequest, opts ...grpc.CallOption) (*CreateLoginResponse, error) {
	out := new(CreateLoginResponse)
	err := c.cc.Invoke(ctx, Logins_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginsClient) Read(ctx context.Context, in *ReadLoginRequest, opts ...grpc.CallOption) (*ReadLoginResponse, error) {
	out := new(ReadLoginResponse)
	err := c.cc.Invoke(ctx, Logins_Read_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginsClient) List(ctx context.Context, in *ReadLoginRequest, opts ...grpc.CallOption) (*ReadLoginResponse, error) {
	out := new(ReadLoginResponse)
	err := c.cc.Invoke(ctx, Logins_List_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginsClient) Upsert(ctx context.Context, in *UpsertLoginRequest, opts ...grpc.CallOption) (*UpsertLoginResponse, error) {
	out := new(UpsertLoginResponse)
	err := c.cc.Invoke(ctx, Logins_Upsert_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginsClient) Delete(ctx context.Context, in *DeleteLoginRequest, opts ...grpc.CallOption) (*DeleteLoginResponse, error) {
	out := new(DeleteLoginResponse)
	err := c.cc.Invoke(ctx, Logins_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginsServer is the server API for Logins service.
// All implementations must embed UnimplementedLoginsServer
// for forward compatibility
type LoginsServer interface {
	Create(context.Context, *CreateLoginRequest) (*CreateLoginResponse, error)
	Read(context.Context, *ReadLoginRequest) (*ReadLoginResponse, error)
	List(context.Context, *ReadLoginRequest) (*ReadLoginResponse, error)
	Upsert(context.Context, *UpsertLoginRequest) (*UpsertLoginResponse, error)
	Delete(context.Context, *DeleteLoginRequest) (*DeleteLoginResponse, error)
	mustEmbedUnimplementedLoginsServer()
}

// UnimplementedLoginsServer must be embedded to have forward compatible implementations.
type UnimplementedLoginsServer struct {
}

func (UnimplementedLoginsServer) Create(context.Context, *CreateLoginRequest) (*CreateLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedLoginsServer) Read(context.Context, *ReadLoginRequest) (*ReadLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedLoginsServer) List(context.Context, *ReadLoginRequest) (*ReadLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedLoginsServer) Upsert(context.Context, *UpsertLoginRequest) (*UpsertLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upsert not implemented")
}
func (UnimplementedLoginsServer) Delete(context.Context, *DeleteLoginRequest) (*DeleteLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedLoginsServer) mustEmbedUnimplementedLoginsServer() {}

// UnsafeLoginsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoginsServer will
// result in compilation errors.
type UnsafeLoginsServer interface {
	mustEmbedUnimplementedLoginsServer()
}

func RegisterLoginsServer(s grpc.ServiceRegistrar, srv LoginsServer) {
	s.RegisterService(&Logins_ServiceDesc, srv)
}

func _Logins_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Logins_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginsServer).Create(ctx, req.(*CreateLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logins_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginsServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Logins_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginsServer).Read(ctx, req.(*ReadLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logins_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Logins_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginsServer).List(ctx, req.(*ReadLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logins_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginsServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Logins_Upsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginsServer).Upsert(ctx, req.(*UpsertLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logins_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Logins_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginsServer).Delete(ctx, req.(*DeleteLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Logins_ServiceDesc is the grpc.ServiceDesc for Logins service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Logins_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "credentials.Logins",
	HandlerType: (*LoginsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Logins_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Logins_Read_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Logins_List_Handler,
		},
		{
			MethodName: "Upsert",
			Handler:    _Logins_Upsert_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Logins_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "credential/pb/rpc/logins.proto",
}
