package pb



import (
	"github.com/gofrs/uuid"
	"gorm.io/gorm"
)



// BeforeCreate - GORM-specific autogenerated helpers.
func (filesystem *FileSystemORM) BeforeCreate(tx *gorm.DB) (err error) {
	// Preserve an explicitly-set primary key: only generate one when none was provided. This
	// lets callers assign a deliberate/shared Id (e.g. one provenance.Source row shared by all
	// the objects a single scan produced) instead of every insert minting a fresh uuid.
	if filesystem.Id != "" {
		return nil
	}
    id, err := uuid.NewV4()
	if err != nil {
		return err
	}
    filesystem.Id = id.String()

    return nil
}



// BeforeCreate - GORM-specific autogenerated helpers.
func (file *FileORM) BeforeCreate(tx *gorm.DB) (err error) {
	// Preserve an explicitly-set primary key: only generate one when none was provided. This
	// lets callers assign a deliberate/shared Id (e.g. one provenance.Source row shared by all
	// the objects a single scan produced) instead of every insert minting a fresh uuid.
	if file.Id != "" {
		return nil
	}
    id, err := uuid.NewV4()
	if err != nil {
		return err
	}
    file.Id = id.String()

    return nil
}



