package nmap



import (
	"github.com/gofrs/uuid"
	"gorm.io/gorm"
)



// BeforeCreate - GORM-specific autogenerated helpers.
func (script *ScriptORM) BeforeCreate(tx *gorm.DB) (err error) {
    id, err := uuid.NewV4()
	if err != nil {
		return err
	}
    script.Id = id.String()

    return nil
}



// BeforeCreate - GORM-specific autogenerated helpers.
func (element *ElementORM) BeforeCreate(tx *gorm.DB) (err error) {
    id, err := uuid.NewV4()
	if err != nil {
		return err
	}
    element.Id = id.String()

    return nil
}



// BeforeCreate - GORM-specific autogenerated helpers.
func (table *TableORM) BeforeCreate(tx *gorm.DB) (err error) {
    id, err := uuid.NewV4()
	if err != nil {
		return err
	}
    table.Id = id.String()

    return nil
}



// BeforeCreate - GORM-specific autogenerated helpers.
func (smurf *SmurfORM) BeforeCreate(tx *gorm.DB) (err error) {
    id, err := uuid.NewV4()
	if err != nil {
		return err
	}
    smurf.Id = id.String()

    return nil
}



