package nmap



import (
	"github.com/gofrs/uuid"
	"gorm.io/gorm"
)



// BeforeCreate - GORM-specific autogenerated helpers.
func (script *ScriptORM) BeforeCreate(tx *gorm.DB) (err error) {
	// Preserve an explicitly-set primary key: only generate one when none was provided. This
	// lets callers assign a deliberate/shared Id (e.g. one provenance.Source row shared by all
	// the objects a single scan produced) instead of every insert minting a fresh uuid.
	if script.Id != "" {
		return nil
	}
    id, err := uuid.NewV4()
	if err != nil {
		return err
	}
    script.Id = id.String()

    return nil
}



// BeforeCreate - GORM-specific autogenerated helpers.
func (element *ElementORM) BeforeCreate(tx *gorm.DB) (err error) {
	// Preserve an explicitly-set primary key: only generate one when none was provided. This
	// lets callers assign a deliberate/shared Id (e.g. one provenance.Source row shared by all
	// the objects a single scan produced) instead of every insert minting a fresh uuid.
	if element.Id != "" {
		return nil
	}
    id, err := uuid.NewV4()
	if err != nil {
		return err
	}
    element.Id = id.String()

    return nil
}



// BeforeCreate - GORM-specific autogenerated helpers.
func (table *TableORM) BeforeCreate(tx *gorm.DB) (err error) {
	// Preserve an explicitly-set primary key: only generate one when none was provided. This
	// lets callers assign a deliberate/shared Id (e.g. one provenance.Source row shared by all
	// the objects a single scan produced) instead of every insert minting a fresh uuid.
	if table.Id != "" {
		return nil
	}
    id, err := uuid.NewV4()
	if err != nil {
		return err
	}
    table.Id = id.String()

    return nil
}



// BeforeCreate - GORM-specific autogenerated helpers.
func (smurf *SmurfORM) BeforeCreate(tx *gorm.DB) (err error) {
	// Preserve an explicitly-set primary key: only generate one when none was provided. This
	// lets callers assign a deliberate/shared Id (e.g. one provenance.Source row shared by all
	// the objects a single scan produced) instead of every insert minting a fresh uuid.
	if smurf.Id != "" {
		return nil
	}
    id, err := uuid.NewV4()
	if err != nil {
		return err
	}
    smurf.Id = id.String()

    return nil
}



