// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.18.1
// source: c2/pb/rpc/channels.proto

package rpc

import (
	pb "github.com/d3c3ptive/aims/c2/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChannelFilters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxResults int64 `protobuf:"varint,1,opt,name=MaxResults,proto3" json:"MaxResults,omitempty"`
}

func (x *ChannelFilters) Reset() {
	*x = ChannelFilters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c2_pb_rpc_channels_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChannelFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelFilters) ProtoMessage() {}

func (x *ChannelFilters) ProtoReflect() protoreflect.Message {
	mi := &file_c2_pb_rpc_channels_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelFilters.ProtoReflect.Descriptor instead.
func (*ChannelFilters) Descriptor() ([]byte, []int) {
	return file_c2_pb_rpc_channels_proto_rawDescGZIP(), []int{0}
}

func (x *ChannelFilters) GetMaxResults() int64 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

type CreateChannelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filters  *ChannelFilters `protobuf:"bytes,1,opt,name=Filters,proto3" json:"Filters,omitempty"`
	Channels []*pb.Channel   `protobuf:"bytes,2,rep,name=Channels,proto3" json:"Channels,omitempty"`
}

func (x *CreateChannelRequest) Reset() {
	*x = CreateChannelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c2_pb_rpc_channels_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChannelRequest) ProtoMessage() {}

func (x *CreateChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_c2_pb_rpc_channels_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChannelRequest.ProtoReflect.Descriptor instead.
func (*CreateChannelRequest) Descriptor() ([]byte, []int) {
	return file_c2_pb_rpc_channels_proto_rawDescGZIP(), []int{1}
}

func (x *CreateChannelRequest) GetFilters() *ChannelFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *CreateChannelRequest) GetChannels() []*pb.Channel {
	if x != nil {
		return x.Channels
	}
	return nil
}

type CreateChannelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channels []*pb.Channel `protobuf:"bytes,1,rep,name=Channels,proto3" json:"Channels,omitempty"`
}

func (x *CreateChannelResponse) Reset() {
	*x = CreateChannelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c2_pb_rpc_channels_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChannelResponse) ProtoMessage() {}

func (x *CreateChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_c2_pb_rpc_channels_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChannelResponse.ProtoReflect.Descriptor instead.
func (*CreateChannelResponse) Descriptor() ([]byte, []int) {
	return file_c2_pb_rpc_channels_proto_rawDescGZIP(), []int{2}
}

func (x *CreateChannelResponse) GetChannels() []*pb.Channel {
	if x != nil {
		return x.Channels
	}
	return nil
}

type ReadChannelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filters *ChannelFilters `protobuf:"bytes,1,opt,name=Filters,proto3" json:"Filters,omitempty"`
	Channel *pb.Channel     `protobuf:"bytes,2,opt,name=Channel,proto3" json:"Channel,omitempty"`
}

func (x *ReadChannelRequest) Reset() {
	*x = ReadChannelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c2_pb_rpc_channels_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadChannelRequest) ProtoMessage() {}

func (x *ReadChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_c2_pb_rpc_channels_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadChannelRequest.ProtoReflect.Descriptor instead.
func (*ReadChannelRequest) Descriptor() ([]byte, []int) {
	return file_c2_pb_rpc_channels_proto_rawDescGZIP(), []int{3}
}

func (x *ReadChannelRequest) GetFilters() *ChannelFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *ReadChannelRequest) GetChannel() *pb.Channel {
	if x != nil {
		return x.Channel
	}
	return nil
}

type ReadChannelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channels []*pb.Channel `protobuf:"bytes,1,rep,name=Channels,proto3" json:"Channels,omitempty"`
}

func (x *ReadChannelResponse) Reset() {
	*x = ReadChannelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c2_pb_rpc_channels_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadChannelResponse) ProtoMessage() {}

func (x *ReadChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_c2_pb_rpc_channels_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadChannelResponse.ProtoReflect.Descriptor instead.
func (*ReadChannelResponse) Descriptor() ([]byte, []int) {
	return file_c2_pb_rpc_channels_proto_rawDescGZIP(), []int{4}
}

func (x *ReadChannelResponse) GetChannels() []*pb.Channel {
	if x != nil {
		return x.Channels
	}
	return nil
}

type UpsertChannelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filters  *ChannelFilters `protobuf:"bytes,1,opt,name=Filters,proto3" json:"Filters,omitempty"`
	Channels []*pb.Channel   `protobuf:"bytes,2,rep,name=Channels,proto3" json:"Channels,omitempty"`
}

func (x *UpsertChannelRequest) Reset() {
	*x = UpsertChannelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c2_pb_rpc_channels_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertChannelRequest) ProtoMessage() {}

func (x *UpsertChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_c2_pb_rpc_channels_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertChannelRequest.ProtoReflect.Descriptor instead.
func (*UpsertChannelRequest) Descriptor() ([]byte, []int) {
	return file_c2_pb_rpc_channels_proto_rawDescGZIP(), []int{5}
}

func (x *UpsertChannelRequest) GetFilters() *ChannelFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *UpsertChannelRequest) GetChannels() []*pb.Channel {
	if x != nil {
		return x.Channels
	}
	return nil
}

type UpsertChannelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channels []*pb.Channel `protobuf:"bytes,1,rep,name=Channels,proto3" json:"Channels,omitempty"`
}

func (x *UpsertChannelResponse) Reset() {
	*x = UpsertChannelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c2_pb_rpc_channels_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertChannelResponse) ProtoMessage() {}

func (x *UpsertChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_c2_pb_rpc_channels_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertChannelResponse.ProtoReflect.Descriptor instead.
func (*UpsertChannelResponse) Descriptor() ([]byte, []int) {
	return file_c2_pb_rpc_channels_proto_rawDescGZIP(), []int{6}
}

func (x *UpsertChannelResponse) GetChannels() []*pb.Channel {
	if x != nil {
		return x.Channels
	}
	return nil
}

type DeleteChannelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channels []*pb.Channel `protobuf:"bytes,1,rep,name=Channels,proto3" json:"Channels,omitempty"`
}

func (x *DeleteChannelRequest) Reset() {
	*x = DeleteChannelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c2_pb_rpc_channels_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChannelRequest) ProtoMessage() {}

func (x *DeleteChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_c2_pb_rpc_channels_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChannelRequest.ProtoReflect.Descriptor instead.
func (*DeleteChannelRequest) Descriptor() ([]byte, []int) {
	return file_c2_pb_rpc_channels_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteChannelRequest) GetChannels() []*pb.Channel {
	if x != nil {
		return x.Channels
	}
	return nil
}

type DeleteChannelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channels []*pb.Channel `protobuf:"bytes,1,rep,name=Channels,proto3" json:"Channels,omitempty"`
}

func (x *DeleteChannelResponse) Reset() {
	*x = DeleteChannelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c2_pb_rpc_channels_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChannelResponse) ProtoMessage() {}

func (x *DeleteChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_c2_pb_rpc_channels_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChannelResponse.ProtoReflect.Descriptor instead.
func (*DeleteChannelResponse) Descriptor() ([]byte, []int) {
	return file_c2_pb_rpc_channels_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteChannelResponse) GetChannels() []*pb.Channel {
	if x != nil {
		return x.Channels
	}
	return nil
}

var File_c2_pb_rpc_channels_proto protoreflect.FileDescriptor

var file_c2_pb_rpc_channels_proto_rawDesc = []byte{
	0x0a, 0x18, 0x63, 0x32, 0x2f, 0x70, 0x62, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x63, 0x32, 0x1a, 0x13,
	0x63, 0x32, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x4d, 0x61, 0x78, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x4d, 0x61, 0x78, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x6d, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a,
	0x07, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x63, 0x32, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x73, 0x52, 0x07, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x12, 0x27, 0x0a, 0x08, 0x43,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x63, 0x32, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x08, 0x43, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x73, 0x22, 0x40, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a,
	0x08, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x63, 0x32, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x08, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x22, 0x69, 0x0a, 0x12, 0x52, 0x65, 0x61, 0x64, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x07,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x63, 0x32, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x73, 0x52, 0x07, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x12, 0x25, 0x0a, 0x07, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x63, 0x32,
	0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x07, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x22, 0x3e, 0x0a, 0x13, 0x52, 0x65, 0x61, 0x64, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x08, 0x43, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x63, 0x32, 0x2e,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x08, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x73, 0x22, 0x6d, 0x0a, 0x14, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x07, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x32, 0x2e,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x52, 0x07,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x12, 0x27, 0x0a, 0x08, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x63, 0x32, 0x2e, 0x43,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x08, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73,
	0x22, 0x40, 0x0a, 0x15, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x08, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x63, 0x32,
	0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x08, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x73, 0x22, 0x3f, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x08, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x63,
	0x32, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x08, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x73, 0x22, 0x40, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x08,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x63, 0x32, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x08, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x32, 0x88, 0x02, 0x0a, 0x08, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x73, 0x12, 0x3f, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x18, 0x2e, 0x63,
	0x32, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x63, 0x32, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x04, 0x52, 0x65, 0x61, 0x64, 0x12, 0x16, 0x2e, 0x63, 0x32,
	0x2e, 0x52, 0x65, 0x61, 0x64, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x63, 0x32, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3f,
	0x0a, 0x06, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x12, 0x18, 0x2e, 0x63, 0x32, 0x2e, 0x55, 0x70,
	0x73, 0x65, 0x72, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x19, 0x2e, 0x63, 0x32, 0x2e, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x3f, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x18, 0x2e, 0x63, 0x32, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x63, 0x32, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x64, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x32, 0x42, 0x0d, 0x43, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x23, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x33, 0x63, 0x33, 0x70, 0x74, 0x69, 0x76,
	0x65, 0x2f, 0x61, 0x69, 0x6d, 0x73, 0x2f, 0x63, 0x32, 0x2f, 0x70, 0x62, 0x2f, 0x72, 0x70, 0x63,
	0xa2, 0x02, 0x03, 0x43, 0x58, 0x58, 0xaa, 0x02, 0x02, 0x43, 0x32, 0xca, 0x02, 0x02, 0x43, 0x32,
	0xe2, 0x02, 0x0e, 0x43, 0x32, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0xea, 0x02, 0x02, 0x43, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_c2_pb_rpc_channels_proto_rawDescOnce sync.Once
	file_c2_pb_rpc_channels_proto_rawDescData = file_c2_pb_rpc_channels_proto_rawDesc
)

func file_c2_pb_rpc_channels_proto_rawDescGZIP() []byte {
	file_c2_pb_rpc_channels_proto_rawDescOnce.Do(func() {
		file_c2_pb_rpc_channels_proto_rawDescData = protoimpl.X.CompressGZIP(file_c2_pb_rpc_channels_proto_rawDescData)
	})
	return file_c2_pb_rpc_channels_proto_rawDescData
}

var file_c2_pb_rpc_channels_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_c2_pb_rpc_channels_proto_goTypes = []interface{}{
	(*ChannelFilters)(nil),        // 0: c2.ChannelFilters
	(*CreateChannelRequest)(nil),  // 1: c2.CreateChannelRequest
	(*CreateChannelResponse)(nil), // 2: c2.CreateChannelResponse
	(*ReadChannelRequest)(nil),    // 3: c2.ReadChannelRequest
	(*ReadChannelResponse)(nil),   // 4: c2.ReadChannelResponse
	(*UpsertChannelRequest)(nil),  // 5: c2.UpsertChannelRequest
	(*UpsertChannelResponse)(nil), // 6: c2.UpsertChannelResponse
	(*DeleteChannelRequest)(nil),  // 7: c2.DeleteChannelRequest
	(*DeleteChannelResponse)(nil), // 8: c2.DeleteChannelResponse
	(*pb.Channel)(nil),            // 9: c2.Channel
}
var file_c2_pb_rpc_channels_proto_depIdxs = []int32{
	0,  // 0: c2.CreateChannelRequest.Filters:type_name -> c2.ChannelFilters
	9,  // 1: c2.CreateChannelRequest.Channels:type_name -> c2.Channel
	9,  // 2: c2.CreateChannelResponse.Channels:type_name -> c2.Channel
	0,  // 3: c2.ReadChannelRequest.Filters:type_name -> c2.ChannelFilters
	9,  // 4: c2.ReadChannelRequest.Channel:type_name -> c2.Channel
	9,  // 5: c2.ReadChannelResponse.Channels:type_name -> c2.Channel
	0,  // 6: c2.UpsertChannelRequest.Filters:type_name -> c2.ChannelFilters
	9,  // 7: c2.UpsertChannelRequest.Channels:type_name -> c2.Channel
	9,  // 8: c2.UpsertChannelResponse.Channels:type_name -> c2.Channel
	9,  // 9: c2.DeleteChannelRequest.Channels:type_name -> c2.Channel
	9,  // 10: c2.DeleteChannelResponse.Channels:type_name -> c2.Channel
	1,  // 11: c2.Channels.Create:input_type -> c2.CreateChannelRequest
	3,  // 12: c2.Channels.Read:input_type -> c2.ReadChannelRequest
	5,  // 13: c2.Channels.Upsert:input_type -> c2.UpsertChannelRequest
	7,  // 14: c2.Channels.Delete:input_type -> c2.DeleteChannelRequest
	2,  // 15: c2.Channels.Create:output_type -> c2.CreateChannelResponse
	4,  // 16: c2.Channels.Read:output_type -> c2.ReadChannelResponse
	6,  // 17: c2.Channels.Upsert:output_type -> c2.UpsertChannelResponse
	8,  // 18: c2.Channels.Delete:output_type -> c2.DeleteChannelResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_c2_pb_rpc_channels_proto_init() }
func file_c2_pb_rpc_channels_proto_init() {
	if File_c2_pb_rpc_channels_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_c2_pb_rpc_channels_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChannelFilters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c2_pb_rpc_channels_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateChannelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c2_pb_rpc_channels_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateChannelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c2_pb_rpc_channels_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadChannelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c2_pb_rpc_channels_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadChannelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c2_pb_rpc_channels_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpsertChannelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c2_pb_rpc_channels_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpsertChannelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c2_pb_rpc_channels_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteChannelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c2_pb_rpc_channels_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteChannelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_c2_pb_rpc_channels_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_c2_pb_rpc_channels_proto_goTypes,
		DependencyIndexes: file_c2_pb_rpc_channels_proto_depIdxs,
		MessageInfos:      file_c2_pb_rpc_channels_proto_msgTypes,
	}.Build()
	File_c2_pb_rpc_channels_proto = out.File
	file_c2_pb_rpc_channels_proto_rawDesc = nil
	file_c2_pb_rpc_channels_proto_goTypes = nil
	file_c2_pb_rpc_channels_proto_depIdxs = nil
}
