// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.18.1
// source: provenance/pb/source.proto

package pb

import (
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SourceType - The class of a provenance Source. Generalizes credential.OriginType
// (Manual / Import / CrackedPassword / Service) with the scan- and c2-oriented producers.
type SourceType int32

const (
	// Manual - A manually added object (CLI arguments, API calls, hand entry).
	SourceType_Manual SourceType = 0
	// Import - Objects loaded from a file (nmap XML, a JSON/XML export, a credential dump).
	SourceType_Import SourceType = 1
	// Cracked - Credentials cracked from another credential.Core.
	// (credential.OriginType.CrackedPassword.)
	SourceType_Cracked SourceType = 2
	// Service - Objects gathered by interacting with a live service
	// (e.g. Metasploit auxiliary/exploit modules). (credential.OriginType.Service.)
	SourceType_Service SourceType = 3
	// Scan - Objects produced by a scanner run (scan.Run: nmap, sx, zgrab, ...).
	SourceType_Scan SourceType = 4
	// C2 - Objects produced by a command-and-control implant/framework (c2.Agent).
	SourceType_C2 SourceType = 5
)

// Enum value maps for SourceType.
var (
	SourceType_name = map[int32]string{
		0: "Manual",
		1: "Import",
		2: "Cracked",
		3: "Service",
		4: "Scan",
		5: "C2",
	}
	SourceType_value = map[string]int32{
		"Manual":  0,
		"Import":  1,
		"Cracked": 2,
		"Service": 3,
		"Scan":    4,
		"C2":      5,
	}
)

func (x SourceType) Enum() *SourceType {
	p := new(SourceType)
	*p = x
	return p
}

func (x SourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_provenance_pb_source_proto_enumTypes[0].Descriptor()
}

func (SourceType) Type() protoreflect.EnumType {
	return &file_provenance_pb_source_proto_enumTypes[0]
}

func (x SourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SourceType.Descriptor instead.
func (SourceType) EnumDescriptor() ([]byte, []int) {
	return file_provenance_pb_source_proto_rawDescGZIP(), []int{0}
}

// Source - A single contribution event: one tool (scanner, C2 framework, cracker,
// manual entry, or file import) writing objects into the shared AIMS store. Every
// merge-unit object — host.Host, host.Port, network.Service, network.Address,
// credential.Core, credential.Login — is joined many-to-many to the Sources that
// contributed or enriched it. This lets a tool that consumes AIMS as a library scope a
// query to only the data it produced ("give me my objects"), and — crucially for the
// "many tools, one object instance" thesis — lets provenance survive the merge fold as a
// UNION of contributors rather than being overwritten by the last writer.
//
// Source generalizes credential.Origin (its Type / Cracker / Filename / SessionId /
// Service fields are carried here) into one cross-domain provenance object. The rich
// per-domain producers — scan.Run (Scanner/Args/Version/ProfileName) and c2.Agent (Tool)
// — are specializations that own a Source; the enum SourceType folds credential.OriginType
// together with the scan and c2 producer classes.
type Source struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: display:"ID" readonly:"true" strict:"yes"
	Id string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty" display:"ID" readonly:"true" strict:"yes"`
	// @gotags: display:"Created at" readonly:"true"
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty" display:"Created at" readonly:"true"`
	// @gotags: display:"Updated at" readonly:"true"
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty" display:"Updated at" readonly:"true"`
	// Tool - The name of the contributing tool ("nmap", "metasploit", "sliver",
	// "hashcat", ...). Empty for a manual/API contribution. This is the primary key a
	// consuming tool filters on to scope a query to its own data.
	// @gotags: display:"Tool"
	Tool string `protobuf:"bytes,10,opt,name=Tool,proto3" json:"Tool,omitempty" display:"Tool"`
	// Type - The class of contribution (manual, import, scan, cracked, service, c2).
	// @gotags: display:"Type"
	Type SourceType `protobuf:"varint,11,opt,name=Type,proto3,enum=provenance.SourceType" json:"Type,omitempty" display:"Type"`
	// SessionId - The attacker-infrastructure session/operator the contribution ran under.
	// (Carried over from credential.Origin.SessionId and scan.Run.SessionId.)
	SessionId string `protobuf:"bytes,12,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	// Version - The version of the contributing tool. (From scan.Run.Version.)
	// @gotags: display:"Version"
	Version string `protobuf:"bytes,13,opt,name=Version,proto3" json:"Version,omitempty" display:"Version"`
	// Args - The full invocation/arguments that produced the contribution — e.g. the raw
	// nmap args. (From scan.Run.Args.)
	Args string `protobuf:"bytes,14,opt,name=Args,proto3" json:"Args,omitempty"`
	// ProfileName - A named profile/preset the tool ran under, if any. (From scan.Run.ProfileName.)
	ProfileName string `protobuf:"bytes,15,opt,name=ProfileName,proto3" json:"ProfileName,omitempty"`
	// Filename - For imports: the basename of the file the objects were loaded from.
	// Because only a basename is available, a Filename may recur across contributions.
	// (Carried over from credential.Origin.Filename.)
	// @gotags: display:"File"
	Filename string `protobuf:"bytes,20,opt,name=Filename,proto3" json:"Filename,omitempty" display:"File"`
	// Cracker - For cracked credentials: the name of the cracking tool.
	// (Carried over from credential.Origin.Cracker.)
	Cracker string `protobuf:"bytes,30,opt,name=Cracker,proto3" json:"Cracker,omitempty"`
	// ServiceId - Soft reference (uuid) to the network.Service the objects were gathered
	// from, when applicable (mirrors credential.Origin.Service). Held as a plain id rather
	// than a belongs_to relation on purpose: network.Service carries its own `Sources`
	// m2m back to this type, and a real relation here would create a proto import cycle
	// (provenance <-> network). Resolve it via a Service query when the full object is needed.
	ServiceId string `protobuf:"bytes,40,opt,name=ServiceId,proto3" json:"ServiceId,omitempty"`
}

func (x *Source) Reset() {
	*x = Source{}
	if protoimpl.UnsafeEnabled {
		mi := &file_provenance_pb_source_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_provenance_pb_source_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_provenance_pb_source_proto_rawDescGZIP(), []int{0}
}

func (x *Source) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Source) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Source) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Source) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *Source) GetType() SourceType {
	if x != nil {
		return x.Type
	}
	return SourceType_Manual
}

func (x *Source) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Source) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Source) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

func (x *Source) GetProfileName() string {
	if x != nil {
		return x.ProfileName
	}
	return ""
}

func (x *Source) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Source) GetCracker() string {
	if x != nil {
		return x.Cracker
	}
	return ""
}

func (x *Source) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

var File_provenance_pb_source_proto protoreflect.FileDescriptor

var file_provenance_pb_source_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2f, 0x70, 0x62, 0x2f,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70, 0x72,
	0x6f, 0x76, 0x65, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2f, 0x67, 0x6f, 0x72, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb4, 0x03,
	0x0a, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x42, 0x0e, 0xba, 0xb9, 0x19, 0x0a, 0x0a, 0x08, 0x12, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x28, 0x01, 0x52, 0x02, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x54, 0x6f, 0x6f, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x6f, 0x6f, 0x6c,
	0x12, 0x2a, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16,
	0x2e, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x41, 0x72, 0x67, 0x73, 0x18, 0x0e, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x41, 0x72, 0x67, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x50,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69,
	0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x14, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x69,
	0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x72, 0x61, 0x63, 0x6b, 0x65,
	0x72, 0x18, 0x1e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72,
	0x12, 0x2a, 0x0a, 0x09, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x28, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x0c, 0xba, 0xb9, 0x19, 0x08, 0x0a, 0x06, 0x12, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x52, 0x09, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x3a, 0x06, 0xba, 0xb9,
	0x19, 0x02, 0x08, 0x01, 0x2a, 0x50, 0x0a, 0x0a, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x10, 0x00, 0x12, 0x0a,
	0x0a, 0x06, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x72,
	0x61, 0x63, 0x6b, 0x65, 0x64, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x63, 0x61, 0x6e, 0x10, 0x04, 0x12, 0x06,
	0x0a, 0x02, 0x43, 0x32, 0x10, 0x05, 0x42, 0x8e, 0x01, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x2e, 0x70,
	0x72, 0x6f, 0x76, 0x65, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x42, 0x0b, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x33, 0x63, 0x33, 0x70, 0x74, 0x69, 0x76, 0x65, 0x2f, 0x61,
	0x69, 0x6d, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2f, 0x70,
	0x62, 0xa2, 0x02, 0x03, 0x50, 0x58, 0x58, 0xaa, 0x02, 0x0a, 0x50, 0x72, 0x6f, 0x76, 0x65, 0x6e,
	0x61, 0x6e, 0x63, 0x65, 0xca, 0x02, 0x0a, 0x50, 0x72, 0x6f, 0x76, 0x65, 0x6e, 0x61, 0x6e, 0x63,
	0x65, 0xe2, 0x02, 0x16, 0x50, 0x72, 0x6f, 0x76, 0x65, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x5c, 0x47,
	0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0a, 0x50, 0x72, 0x6f,
	0x76, 0x65, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_provenance_pb_source_proto_rawDescOnce sync.Once
	file_provenance_pb_source_proto_rawDescData = file_provenance_pb_source_proto_rawDesc
)

func file_provenance_pb_source_proto_rawDescGZIP() []byte {
	file_provenance_pb_source_proto_rawDescOnce.Do(func() {
		file_provenance_pb_source_proto_rawDescData = protoimpl.X.CompressGZIP(file_provenance_pb_source_proto_rawDescData)
	})
	return file_provenance_pb_source_proto_rawDescData
}

var file_provenance_pb_source_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_provenance_pb_source_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_provenance_pb_source_proto_goTypes = []interface{}{
	(SourceType)(0),               // 0: provenance.SourceType
	(*Source)(nil),                // 1: provenance.Source
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_provenance_pb_source_proto_depIdxs = []int32{
	2, // 0: provenance.Source.CreatedAt:type_name -> google.protobuf.Timestamp
	2, // 1: provenance.Source.UpdatedAt:type_name -> google.protobuf.Timestamp
	0, // 2: provenance.Source.Type:type_name -> provenance.SourceType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_provenance_pb_source_proto_init() }
func file_provenance_pb_source_proto_init() {
	if File_provenance_pb_source_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_provenance_pb_source_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Source); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_provenance_pb_source_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_provenance_pb_source_proto_goTypes,
		DependencyIndexes: file_provenance_pb_source_proto_depIdxs,
		EnumInfos:         file_provenance_pb_source_proto_enumTypes,
		MessageInfos:      file_provenance_pb_source_proto_msgTypes,
	}.Build()
	File_provenance_pb_source_proto = out.File
	file_provenance_pb_source_proto_rawDesc = nil
	file_provenance_pb_source_proto_goTypes = nil
	file_provenance_pb_source_proto_depIdxs = nil
}
